// Code generated by ent, DO NOT EDIT.

package alertescalation

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the alertescalation type in the database.
	Label = "alert_escalation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAlertID holds the string denoting the alert_id field in the database.
	FieldAlertID = "alert_id"
	// FieldRuleID holds the string denoting the rule_id field in the database.
	FieldRuleID = "rule_id"
	// FieldCurrentLevel holds the string denoting the current_level field in the database.
	FieldCurrentLevel = "current_level"
	// FieldMaxLevel holds the string denoting the max_level field in the database.
	FieldMaxLevel = "max_level"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNextEscalationAt holds the string denoting the next_escalation_at field in the database.
	FieldNextEscalationAt = "next_escalation_at"
	// FieldEscalationDelaySeconds holds the string denoting the escalation_delay_seconds field in the database.
	FieldEscalationDelaySeconds = "escalation_delay_seconds"
	// FieldRepeatIntervalSeconds holds the string denoting the repeat_interval_seconds field in the database.
	FieldRepeatIntervalSeconds = "repeat_interval_seconds"
	// FieldAdditionalChannels holds the string denoting the additional_channels field in the database.
	FieldAdditionalChannels = "additional_channels"
	// FieldResolvedAt holds the string denoting the resolved_at field in the database.
	FieldResolvedAt = "resolved_at"
	// FieldResolvedBy holds the string denoting the resolved_by field in the database.
	FieldResolvedBy = "resolved_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeAlert holds the string denoting the alert edge name in mutations.
	EdgeAlert = "alert"
	// EdgeRule holds the string denoting the rule edge name in mutations.
	EdgeRule = "rule"
	// Table holds the table name of the alertescalation in the database.
	Table = "alert_escalations"
	// AlertTable is the table that holds the alert relation/edge.
	AlertTable = "alert_escalations"
	// AlertInverseTable is the table name for the Alert entity.
	// It exists in this package in order to avoid circular dependency with the "alert" package.
	AlertInverseTable = "alerts"
	// AlertColumn is the table column denoting the alert relation/edge.
	AlertColumn = "alert_id"
	// RuleTable is the table that holds the rule relation/edge.
	RuleTable = "alert_escalations"
	// RuleInverseTable is the table name for the AlertRule entity.
	// It exists in this package in order to avoid circular dependency with the "alertrule" package.
	RuleInverseTable = "alert_rules"
	// RuleColumn is the table column denoting the rule relation/edge.
	RuleColumn = "rule_id"
)

// Columns holds all SQL columns for alertescalation fields.
var Columns = []string{
	FieldID,
	FieldAlertID,
	FieldRuleID,
	FieldCurrentLevel,
	FieldMaxLevel,
	FieldStatus,
	FieldNextEscalationAt,
	FieldEscalationDelaySeconds,
	FieldRepeatIntervalSeconds,
	FieldAdditionalChannels,
	FieldResolvedAt,
	FieldResolvedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AlertIDValidator is a validator for the "alert_id" field. It is called by the builders before save.
	AlertIDValidator func(string) error
	// RuleIDValidator is a validator for the "rule_id" field. It is called by the builders before save.
	RuleIDValidator func(string) error
	// DefaultCurrentLevel holds the default value on creation for the "current_level" field.
	DefaultCurrentLevel int
	// CurrentLevelValidator is a validator for the "current_level" field. It is called by the builders before save.
	CurrentLevelValidator func(int) error
	// MaxLevelValidator is a validator for the "max_level" field. It is called by the builders before save.
	MaxLevelValidator func(int) error
	// EscalationDelaySecondsValidator is a validator for the "escalation_delay_seconds" field. It is called by the builders before save.
	EscalationDelaySecondsValidator func(int) error
	// ResolvedByValidator is a validator for the "resolved_by" field. It is called by the builders before save.
	ResolvedByValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusPENDING     Status = "PENDING"
	StatusRESOLVED    Status = "RESOLVED"
	StatusMAX_REACHED Status = "MAX_REACHED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusRESOLVED, StatusMAX_REACHED:
		return nil
	default:
		return fmt.Errorf("alertescalation: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the AlertEscalation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAlertID orders the results by the alert_id field.
func ByAlertID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlertID, opts...).ToFunc()
}

// ByRuleID orders the results by the rule_id field.
func ByRuleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleID, opts...).ToFunc()
}

// ByCurrentLevel orders the results by the current_level field.
func ByCurrentLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentLevel, opts...).ToFunc()
}

// ByMaxLevel orders the results by the max_level field.
func ByMaxLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxLevel, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNextEscalationAt orders the results by the next_escalation_at field.
func ByNextEscalationAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextEscalationAt, opts...).ToFunc()
}

// ByEscalationDelaySeconds orders the results by the escalation_delay_seconds field.
func ByEscalationDelaySeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEscalationDelaySeconds, opts...).ToFunc()
}

// ByResolvedAt orders the results by the resolved_at field.
func ByResolvedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedAt, opts...).ToFunc()
}

// ByResolvedBy orders the results by the resolved_by field.
func ByResolvedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAlertField orders the results by alert field.
func ByAlertField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAlertStep(), sql.OrderByField(field, opts...))
	}
}

// ByRuleField orders the results by rule field.
func ByRuleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRuleStep(), sql.OrderByField(field, opts...))
	}
}
func newAlertStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AlertInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AlertTable, AlertColumn),
	)
}
func newRuleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RuleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RuleTable, RuleColumn),
	)
}
