import type { PortSlot, RouterModelDescriptor } from './types';

const eth = (n: number, col: number, extra: Partial<PortSlot> = {}): PortSlot => ({
  id: `eth${n}`,
  kind: 'ethernet',
  ifaceName: `ether${n}`,
  label: String(n),
  nominalSpeed: '1G',
  row: 0,
  col,
  ...extra,
});

export const MODELS: RouterModelDescriptor[] = [
  {
    key: 'hap-ax2',
    displayName: 'MikroTik hAP ax2',
    aliases: ['hapax2', 'c52ig', 'ax2'],
    form: 'tower',
    slots: [
      eth(1, 0, { label: '1·PoE', badge: 'poe' }),
      eth(2, 1),
      eth(3, 2),
      eth(4, 3),
      eth(5, 4),
      { id: 'pwr', kind: 'power', label: 'DC', row: 0, col: 5 },
      { id: 'rst', kind: 'reset', label: 'Reset', row: 0, col: 6 },
    ],
  },
  {
    key: 'hap-ax3',
    displayName: 'MikroTik hAP ax3',
    aliases: ['hapax3', 'c53ui', 'ax3'],
    form: 'desktop',
    slots: [
      eth(1, 0, { label: '1·PoE', badge: 'poe' }),
      eth(2, 1),
      eth(3, 2),
      eth(4, 3),
      eth(5, 4),
      { id: 'usb', kind: 'usb', label: 'USB 3.0', row: 0, col: 5 },
      { id: 'pwr', kind: 'power', label: 'DC', row: 0, col: 6 },
      { id: 'rst', kind: 'reset', label: 'Reset', row: 0, col: 7 },
    ],
  },
  {
    key: 'rb4011',
    displayName: 'MikroTik RB4011iGS+RM',
    aliases: ['rb4011', '4011'],
    form: 'rackmount',
    slots: [
      eth(1, 0, { label: '1·PoE', badge: 'poe' }),
      eth(2, 1),
      eth(3, 2),
      eth(4, 3),
      eth(5, 4),
      eth(6, 5),
      eth(7, 6),
      eth(8, 7),
      eth(9, 8),
      eth(10, 9),
      {
        id: 'sfp1',
        kind: 'sfp',
        ifaceName: 'sfp-sfpplus1',
        label: 'SFP+',
        nominalSpeed: '10G',
        row: 0,
        col: 10,
      },
      { id: 'usb', kind: 'usb', label: 'USB 3.0', row: 0, col: 11 },
      { id: 'pwr', kind: 'power', label: 'DC', row: 0, col: 12 },
      { id: 'rst', kind: 'reset', label: 'Reset', row: 0, col: 13 },
    ],
  },
  {
    key: 'rb5009',
    displayName: 'MikroTik RB5009UG+S+IN',
    aliases: ['rb5009', '5009'],
    form: 'desktop',
    slots: [
      eth(1, 0, { label: '1·PoE', badge: 'poe' }),
      eth(2, 1),
      eth(3, 2),
      eth(4, 3),
      eth(5, 4),
      eth(6, 5),
      eth(7, 6),
      eth(8, 7, { label: '8·2.5G', nominalSpeed: '2.5G' }),
      {
        id: 'sfp1',
        kind: 'sfp',
        ifaceName: 'sfp-sfpplus1',
        label: 'SFP+',
        nominalSpeed: '10G',
        row: 0,
        col: 8,
      },
      { id: 'usb', kind: 'usb', label: 'USB 3.0', row: 0, col: 9 },
      { id: 'pwr', kind: 'power', label: 'DC', row: 0, col: 10 },
      { id: 'rst', kind: 'reset', label: 'Reset', row: 0, col: 11 },
    ],
  },
  {
    key: 'chateau-lte12',
    displayName: 'MikroTik Chateau LTE12',
    aliases: ['chateau', 'lte12', 'd53g', 'rbd53'],
    form: 'desktop',
    slots: [
      eth(1, 0, { label: '1·PoE', badge: 'poe' }),
      eth(2, 1),
      eth(3, 2),
      eth(4, 3),
      eth(5, 4),
      { id: 'usb', kind: 'usb', label: 'USB', row: 0, col: 5 },
      { id: 'sim', kind: 'sim', label: 'SIM', row: 0, col: 6 },
      { id: 'ant1', kind: 'antenna', label: 'LTE 1', row: 0, col: 7 },
      { id: 'ant2', kind: 'antenna', label: 'LTE 2', row: 0, col: 8 },
      { id: 'pwr', kind: 'power', label: 'DC', row: 0, col: 9 },
      { id: 'rst', kind: 'reset', label: 'Reset', row: 0, col: 10 },
    ],
  },
];
