package services

import (
	"fmt"

	cfglib "backend/internal/config"
)

const adguardConfigTemplate = `# AdGuard Home configuration generated by NasNetConnect
# Instance ID: {{.InstanceID}}

bind_host: {{.BindIP}}
bind_port: {{.GetInt "web_port"}}

users:
  - name: {{.GetString "admin_user"}}
    password: {{.GetString "admin_password"}}

dns:
  bind_hosts:
    - {{.BindIP}}
  port: {{.GetInt "dns_port"}}
  upstream_dns:
{{range .GetStringSlice "upstream_dns"}}    - {{.}}
{{end}}
  bootstrap_dns:
{{range .GetStringSlice "bootstrap_dns"}}    - {{.}}
{{end}}
  protection_enabled: {{.GetBool "protection_enabled"}}
  blocking_mode: {{.GetString "blocking_mode"}}
  blocked_response_ttl: 10

filters:
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
    name: AdGuard DNS filter
    id: 1

querylog:
  enabled: {{.GetBool "querylog_enabled"}}
  interval: {{.GetInt "querylog_interval"}}h

statistics:
  enabled: {{.GetBool "statistics_enabled"}}
  interval: {{.GetInt "statistics_interval"}}

dhcp:
  enabled: false

tls:
  enabled: false
`

// AdguardGenerator generates AdGuard Home YAML configuration files.
type AdguardGenerator struct {
	*cfglib.BaseGenerator
}

// NewAdguardGenerator creates a new AdGuard Home config generator.
func NewAdguardGenerator() *AdguardGenerator {
	schema := &cfglib.ConfigSchema{
		ServiceType: "adguard",
		Version:     "1.0.0",
		Fields: []cfglib.ConfigField{
			{
				Name:        "web_port",
				Type:        "port",
				Required:    true,
				Default:     3000,
				Min:         intPtr(1024),
				Max:         intPtr(65535),
				Description: "Web interface port",
			},
			{
				Name:        "dns_port",
				Type:        "port",
				Required:    true,
				Default:     53,
				Min:         intPtr(1),
				Max:         intPtr(65535),
				Description: "DNS server port",
			},
			{
				Name:        "admin_user",
				Type:        "string",
				Required:    true,
				Default:     "admin",
				Description: "Admin username",
			},
			{
				Name:        "admin_password",
				Type:        "string",
				Required:    true,
				Description: "Admin password (bcrypt hash)",
				Sensitive:   true,
			},
			{
				Name:        "upstream_dns",
				Type:        "string",
				Required:    true,
				Default:     "https://dns.cloudflare.com/dns-query,https://dns.google/dns-query",
				Description: "Upstream DNS servers (comma-separated)",
			},
			{
				Name:        "bootstrap_dns",
				Type:        "string",
				Required:    true,
				Default:     "1.1.1.1,8.8.8.8",
				Description: "Bootstrap DNS servers (comma-separated)",
			},
			{
				Name:        "protection_enabled",
				Type:        "bool",
				Required:    true,
				Default:     true,
				Description: "Enable DNS protection",
			},
			{
				Name:        "blocking_mode",
				Type:        "enum",
				Required:    true,
				Default:     "default",
				EnumValues:  []string{"default", "nxdomain", "null_ip", "refused"},
				Description: "Blocking mode for filtered domains",
			},
			{
				Name:        "querylog_enabled",
				Type:        "bool",
				Required:    true,
				Default:     true,
				Description: "Enable query logging",
			},
			{
				Name:        "querylog_interval",
				Type:        "int",
				Required:    true,
				Default:     24,
				Min:         intPtr(1),
				Max:         intPtr(720),
				Description: "Query log retention in hours",
			},
			{
				Name:        "statistics_enabled",
				Type:        "bool",
				Required:    true,
				Default:     true,
				Description: "Enable statistics",
			},
			{
				Name:        "statistics_interval",
				Type:        "int",
				Required:    true,
				Default:     24,
				Min:         intPtr(1),
				Max:         intPtr(720),
				Description: "Statistics retention in hours",
			},
		},
	}

	tmpl := cfglib.MustParseTemplate("adguard", adguardConfigTemplate)

	return &AdguardGenerator{
		BaseGenerator: cfglib.NewBaseGenerator("adguard", schema, tmpl),
	}
}

// Generate generates an AdGuard Home YAML configuration file.
func (g *AdguardGenerator) Generate(instanceID string, config map[string]interface{}, bindIP string) ([]byte, error) {
	// Merge with defaults FIRST
	config = g.Schema.MergeWithDefaults(config)

	// Then validate (after defaults are applied)
	if err := g.Validate(config, bindIP); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}

	// Split comma-separated DNS servers into slices
	upstreamDNS, _ := config["upstream_dns"].(string)
	config["upstream_dns_slice"] = splitCommaSeparated(upstreamDNS)

	bootstrapDNS, _ := config["bootstrap_dns"].(string)
	config["bootstrap_dns_slice"] = splitCommaSeparated(bootstrapDNS)

	// Prepare template data
	data := &AdguardTemplateData{
		TemplateData: cfglib.NewTemplateData(instanceID, bindIP, config),
	}

	// Render template
	return g.RenderTemplate(data)
}

// AdguardTemplateData extends TemplateData with AdGuard-specific helpers.
type AdguardTemplateData struct {
	*cfglib.TemplateData
}

// GetStringSlice retrieves a string slice from config.
func (d *AdguardTemplateData) GetStringSlice(key string) []string {
	// Try the slice version first (e.g., "upstream_dns_slice")
	sliceKey := key + "_slice"
	if val, ok := d.Config[sliceKey].([]string); ok {
		return val
	}

	// Fallback to parsing comma-separated string
	if val, ok := d.Config[key].(string); ok {
		return splitCommaSeparated(val)
	}

	return []string{}
}

// Validate performs AdGuard-specific validation.
func (g *AdguardGenerator) Validate(config map[string]interface{}, bindIP string) error {
	// Base validation (schema + bind IP)
	if err := g.ValidateConfig(config, bindIP); err != nil {
		return err
	}

	// Validate admin username is not empty
	adminUser, _ := config["admin_user"].(string)
	if err := cfglib.ValidateNonEmpty("admin_user", adminUser); err != nil {
		return err
	}

	// Validate admin password is not empty
	adminPassword, _ := config["admin_password"].(string)
	if err := cfglib.ValidateNonEmpty("admin_password", adminPassword); err != nil {
		return err
	}

	return nil
}

// GetConfigFileName returns the filename for the generated config.
func (g *AdguardGenerator) GetConfigFileName() string {
	return "AdGuardHome.yaml"
}

// GetConfigFormat returns the config file format.
func (g *AdguardGenerator) GetConfigFormat() string {
	return "yaml"
}

// splitCommaSeparated splits a comma-separated string into a slice.
func splitCommaSeparated(s string) []string {
	if s == "" {
		return []string{}
	}

	result := []string{}
	parts := []rune(s)
	current := []rune{}

	for _, char := range parts {
		if char == ',' {
			if len(current) > 0 {
				result = append(result, string(current))
				current = []rune{}
			}
		} else if char != ' ' { // Skip spaces
			current = append(current, char)
		}
	}

	if len(current) > 0 {
		result = append(result, string(current))
	}

	return result
}
