package routes

import (
	"nasnet-panel/internal/handler"
	"nasnet-panel/internal/middleware"

	"github.com/labstack/echo/v4"
)

// RegisterRoutes registers all API routes.
func RegisterRoutes(e *echo.Echo) {
	e.GET("/health", handler.HandleHealthCheck)
	initSwagger(e)

	appGroup := e.Group("/api/app")
	appGroup.Use(middleware.RouterOSAuth)
	appGroup.GET("/version", handler.HandleAppVersion)
	appGroup.GET("/check-for-updates", handler.HandleAppCheckForUpdates)
	appGroup.POST("/install-update", handler.HandleAppInstallUpdate)
	appGroup.GET("/update-status", handler.HandleAppUpdateStatus)

	pluginGroup := e.Group("/api/plugin")
	pluginGroup.Use(middleware.RouterOSAuth)
	pluginGroup.GET("/plugins", handler.HandleListPlugins)
	pluginGroup.POST("/install", handler.HandleInstallPlugin)
	pluginGroup.DELETE("/plugin/:name", handler.HandleUninstallPlugin)
	pluginGroup.GET("/status/:pluginId", handler.HandleGetPluginInstallStatus)

	systemGroup := e.Group("/api/system")
	systemGroup.Use(middleware.RouterOSAuth)
	systemGroup.GET("/info", handler.HandleGetSystemInfo)
	systemGroup.GET("/identity", handler.HandleGetSystemIdentity)
	systemGroup.PUT("/identity", handler.HandleSetSystemIdentity)
	systemGroup.GET("/updates", handler.HandleGetSystemUpdates)
	systemGroup.GET("/check-for-updates", handler.HandleCheckForUpdates)
	systemGroup.POST("/install-update", handler.HandleInstallUpdate)
	systemGroup.GET("/resources", handler.HandleGetResourceInfo)
	systemGroup.PUT("/password", handler.HandleChangeUserPassword)
	systemGroup.POST("/reboot", handler.HandleRebootSystem)
	systemGroup.POST("/shutdown", handler.HandleShutdownSystem)

	wifiGroup := e.Group("/api/wifi")
	wifiGroup.Use(middleware.RouterOSAuth)
	wifiGroup.GET("/interfaces", handler.HandleListWiFiInterfaces)
	wifiGroup.GET("/interfaces/:name", handler.HandleGetWiFiInterface)
	wifiGroup.GET("/scan/:nameOrID", handler.HandleScanWiFiAccessPoints)
	wifiGroup.GET("/status/:nameOrID", handler.HandleGetWiFiStatus)
	wifiGroup.POST("/connect/:nameOrID", handler.HandleConnectWiFi)
	wifiGroup.PUT("/interfaces/:name", handler.HandleUpdateWiFiInterface)
	wifiGroup.PUT("/settings/:name", handler.HandleUpdateWiFiSettings)
	wifiGroup.GET("/clients", handler.HandleListWiFiConnectedClients)
	wifiGroup.DELETE("/clients/:mac", handler.HandleRemoveWiFiConnectedClient)
	wifiGroup.GET("/passphrase/:name", handler.HandleGetWiFiPassphrase)
	wifiGroup.PUT("/passphrase/:name", handler.HandleChangeWiFiPassphrase)

	dhcpGroup := e.Group("/api/dhcp")
	dhcpGroup.Use(middleware.RouterOSAuth)
	dhcpGroup.GET("/leases", handler.HandleListDHCPLeases)
	dhcpGroup.POST("/leases/make-static", handler.HandleMakeDHCPLeaseStatic)
	dhcpGroup.DELETE("/leases/:macAddress", handler.HandleRemoveDHCPLease)
	dhcpGroup.GET("/clients", handler.HandleListDHCPClients)
	dhcpGroup.POST("/client/:nameOrID", handler.HandleConfigureDHCPClient)
	dhcpGroup.GET("/servers", handler.HandleListDHCPServers)

	firewallGroup := e.Group("/api/firewall")
	firewallGroup.Use(middleware.RouterOSAuth)
	firewallGroup.GET("/filter", handler.HandleListFirewallFilterRules)

	scanGroup := e.Group("/api/scan")
	scanGroup.POST("", handler.HandleStartScan)
	scanGroup.GET("/status/:taskId", handler.HandleScanStatus)
	scanGroup.POST("/stop", handler.HandleStopScan)
	scanGroup.POST("/auto", handler.HandleAutoScan)
	scanGroup.POST("/verify", handler.HandleVerifyIP)

	logsGroup := e.Group("/api/logs")
	logsGroup.Use(middleware.RouterOSAuth)
	logsGroup.GET("", handler.HandleGetLogs)

	interfaceGroup := e.Group("/api/interface")
	interfaceGroup.Use(middleware.RouterOSAuth)
	interfaceGroup.GET("/interfaces", handler.HandleListInterfaces)
	interfaceGroup.GET("/ethernets", handler.HandleGetEthernetInterfaces)
	interfaceGroup.GET("/ethernet/:nameOrID", handler.HandleGetEthernetInterface)
	interfaceGroup.GET("/graph/:nameOrID", handler.HandleGetInterfaceGraph)
	interfaceGroup.PUT("/wan", handler.HandleUpdateWANInterface)

	dnsGroup := e.Group("/api/dns")
	dnsGroup.Use(middleware.RouterOSAuth)
	dnsGroup.GET("/info", handler.HandleGetDNSInfo)
	dnsGroup.PUT("/info", handler.HandleUpdateDNS)
	dnsGroup.GET("/suggest", handler.HandleSuggestDNS)
	dnsGroup.GET("/validate", handler.HandleValidateDNS)
	dnsGroup.POST("/change", handler.HandleChangeDNS)
	dnsGroup.POST("/reset", handler.HandleResetDNS)

	vpnGroup := e.Group("/api/vpn")
	vpnGroup.Use(middleware.RouterOSAuth)
	vpnGroup.GET("/clients", handler.HandleListVPNClients)
	vpnGroup.GET("/clients/:name", handler.HandleGetVPNClient)
	vpnGroup.PUT("/clients/:name", handler.HandleUpdateVPNClient)
	vpnGroup.POST("/l2tp/client", handler.HandleAddL2TPClient)
	vpnGroup.GET("/l2tp/client/:name", handler.HandleGetL2TPClient)
	vpnGroup.PUT("/l2tp/client/:nameOrID", handler.HandleUpdateL2TPClient)
	vpnGroup.DELETE("/l2tp/client/:nameOrID", handler.HandleDeleteL2TPClient)
	vpnGroup.GET("/servers", handler.HandleListVPNServers)
	vpnGroup.GET("/ovpn/server/:name", handler.HandleGetOvpnServerDetails)
	vpnGroup.POST("/ovpn/server", handler.HandleCreateOvpnServer)
	vpnGroup.GET("/ovpn/server/status/:taskId", handler.HandleGetOvpnServerTaskStatus)
	vpnGroup.DELETE("/ovpn/server/:name", handler.HandleDeleteOvpnServer)
	vpnGroup.GET("/ovpn/server/export", handler.HandleExportOvpnClient)
	vpnGroup.GET("/pptp/server", handler.HandleGetPptpServerDetails)
	vpnGroup.GET("/l2tp/server", handler.HandleGetL2tpServerDetails)
	vpnGroup.GET("/sstp/server", handler.HandleGetSstpServerDetails)
	vpnGroup.POST("/wireguard/client", handler.HandleCreateWireGuardClient)
	vpnGroup.POST("/wireguard/server", handler.HandleCreateWireGuardServer)
	vpnGroup.POST("/wireguard/peer", handler.HandleCreateWireGuardServerPeer)
	vpnGroup.POST("/wireguard/import-config", handler.HandleImportWireGuardConfig)
	vpnGroup.PUT("/wireguard/interface/:nameOrID", handler.HandleUpdateWireGuardInterface)
	vpnGroup.PUT("/wireguard/peer/:nameOrID", handler.HandleUpdateWireGuardPeer)
	vpnGroup.DELETE("/wireguard/peer/:nameOrID", handler.HandleDeleteWireGuardPeer)
	vpnGroup.DELETE("/wireguard/interface/:nameOrID", handler.HandleDeleteWireGuardInterface)
	vpnGroup.GET("/wireguard/detailed/:name", handler.HandleGetWireGuardDetailed)
	vpnGroup.GET("/wireguard/interface/:nameOrID", handler.HandleGetWireGuardInterface)
	vpnGroup.GET("/wireguard/peers/:name", handler.HandleGetWireGuardPeers)
	vpnGroup.GET("/profiles", handler.HandleListVPNProfiles)
	vpnGroup.GET("/users", handler.HandleListVPNUsers)
	vpnGroup.POST("/users", handler.HandleCreateVPNUser)
	vpnGroup.PUT("/users/:nameOrID", handler.HandleUpdateVPNUserByID)
	vpnGroup.DELETE("/users/:nameOrID", handler.HandleDeleteVPNUserByID)

	netGroup := e.Group("/api/net")
	netGroup.Use(middleware.RouterOSAuth)
	netGroup.GET("/status", handler.HandleGetNetStatus)

	wizardGroup := e.Group("/api/wizard")
	wizardGroup.Use(middleware.RouterOSAuth)
	wizardGroup.POST("/vpn", handler.HandleGetVPNCredentials)
	wizardGroup.GET("/status", handler.HandleGetWizardStatus)
	wizardGroup.POST("/finalize", handler.HandleFinalizeWizard)

	routeGroup := e.Group("/api/route")
	routeGroup.Use(middleware.RouterOSAuth)
	routeGroup.GET("/foreign-gateway", handler.HandleGetForeignGateway)
	routeGroup.PUT("/foreign-gateway", handler.HandleUpdateForeignGateway)

	diagGroup := e.Group("/api/diag")
	diagGroup.Use(middleware.RouterOSAuth)
	diagGroup.POST("/generate", handler.HandleGenerateDiag)
	diagGroup.GET("/status", handler.HandleGetDiagStatus)
	diagGroup.GET("/download", handler.HandleDownloadDiag)
}
