// Code generated by ent, DO NOT EDIT.

package serviceinstance

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the serviceinstance type in the database.
	Label = "service_instance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFeatureID holds the string denoting the feature_id field in the database.
	FieldFeatureID = "feature_id"
	// FieldInstanceName holds the string denoting the instance_name field in the database.
	FieldInstanceName = "instance_name"
	// FieldRouterID holds the string denoting the router_id field in the database.
	FieldRouterID = "router_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldVlanID holds the string denoting the vlan_id field in the database.
	FieldVlanID = "vlan_id"
	// FieldBindIP holds the string denoting the bind_ip field in the database.
	FieldBindIP = "bind_ip"
	// FieldPorts holds the string denoting the ports field in the database.
	FieldPorts = "ports"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldBinaryPath holds the string denoting the binary_path field in the database.
	FieldBinaryPath = "binary_path"
	// FieldBinaryVersion holds the string denoting the binary_version field in the database.
	FieldBinaryVersion = "binary_version"
	// FieldBinaryChecksum holds the string denoting the binary_checksum field in the database.
	FieldBinaryChecksum = "binary_checksum"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeRouter holds the string denoting the router edge name in mutations.
	EdgeRouter = "router"
	// Table holds the table name of the serviceinstance in the database.
	Table = "service_instances"
	// RouterTable is the table that holds the router relation/edge.
	RouterTable = "service_instances"
	// RouterInverseTable is the table name for the Router entity.
	// It exists in this package in order to avoid circular dependency with the "router" package.
	RouterInverseTable = "routers"
	// RouterColumn is the table column denoting the router relation/edge.
	RouterColumn = "router_id"
)

// Columns holds all SQL columns for serviceinstance fields.
var Columns = []string{
	FieldID,
	FieldFeatureID,
	FieldInstanceName,
	FieldRouterID,
	FieldStatus,
	FieldVlanID,
	FieldBindIP,
	FieldPorts,
	FieldConfig,
	FieldBinaryPath,
	FieldBinaryVersion,
	FieldBinaryChecksum,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// FeatureIDValidator is a validator for the "feature_id" field. It is called by the builders before save.
	FeatureIDValidator func(string) error
	// InstanceNameValidator is a validator for the "instance_name" field. It is called by the builders before save.
	InstanceNameValidator func(string) error
	// RouterIDValidator is a validator for the "router_id" field. It is called by the builders before save.
	RouterIDValidator func(string) error
	// VlanIDValidator is a validator for the "vlan_id" field. It is called by the builders before save.
	VlanIDValidator func(int) error
	// BindIPValidator is a validator for the "bind_ip" field. It is called by the builders before save.
	BindIPValidator func(string) error
	// BinaryPathValidator is a validator for the "binary_path" field. It is called by the builders before save.
	BinaryPathValidator func(string) error
	// BinaryVersionValidator is a validator for the "binary_version" field. It is called by the builders before save.
	BinaryVersionValidator func(string) error
	// BinaryChecksumValidator is a validator for the "binary_checksum" field. It is called by the builders before save.
	BinaryChecksumValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusInstalling is the default value of the Status enum.
const DefaultStatus = StatusInstalling

// Status values.
const (
	StatusInstalling Status = "installing"
	StatusInstalled  Status = "installed"
	StatusStarting   Status = "starting"
	StatusRunning    Status = "running"
	StatusStopping   Status = "stopping"
	StatusStopped    Status = "stopped"
	StatusFailed     Status = "failed"
	StatusDeleting   Status = "deleting"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusInstalling, StatusInstalled, StatusStarting, StatusRunning, StatusStopping, StatusStopped, StatusFailed, StatusDeleting:
		return nil
	default:
		return fmt.Errorf("serviceinstance: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ServiceInstance queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFeatureID orders the results by the feature_id field.
func ByFeatureID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeatureID, opts...).ToFunc()
}

// ByInstanceName orders the results by the instance_name field.
func ByInstanceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstanceName, opts...).ToFunc()
}

// ByRouterID orders the results by the router_id field.
func ByRouterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRouterID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByVlanID orders the results by the vlan_id field.
func ByVlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVlanID, opts...).ToFunc()
}

// ByBindIP orders the results by the bind_ip field.
func ByBindIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBindIP, opts...).ToFunc()
}

// ByBinaryPath orders the results by the binary_path field.
func ByBinaryPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBinaryPath, opts...).ToFunc()
}

// ByBinaryVersion orders the results by the binary_version field.
func ByBinaryVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBinaryVersion, opts...).ToFunc()
}

// ByBinaryChecksum orders the results by the binary_checksum field.
func ByBinaryChecksum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBinaryChecksum, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRouterField orders the results by router field.
func ByRouterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRouterStep(), sql.OrderByField(field, opts...))
	}
}
func newRouterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RouterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RouterTable, RouterColumn),
	)
}
