import { mockApi, mockStore, getProtocolOptions } from '@nasnet/mocks';
import { scanner } from './scanner';

export const api = {
  ...mockApi,
  scanner,
};
export const store = mockStore;
export { getProtocolOptions };
export {
  verifyIP,
  testCredentials,
  type VerifyResponse,
  type RouterOSVerifyInfo,
  type RouterSystemInfo,
} from './scanner';
export {
  fetchSystemInfo,
  fetchSystemResources,
  fetchDHCPLeases,
  fetchSystemOverview,
  fetchDynamicOverview,
  fetchInterfaceGraph,
  fetchInterfaces,
  fetchEthernetInterfaces,
  updateWanInterface,
  type WanInterfaceType,
  type UpdateWanInterfaceRequest,
  fetchForeignGateway,
  updateForeignGateway,
  type ForeignGatewayResponse,
  fetchVPNClients,
  rebootSystem,
  setSystemIdentity,
  shutdownSystem,
  changeUserPassword,
  type SystemCredentials,
  type SystemInfoResponse,
  type ResourceInfoResponse,
  type DHCPLeaseResponse,
  type DynamicOverview,
  type InterfaceGraphResponse,
  type InterfaceGraphSample,
  type InterfaceResponse,
  type EthernetInterfaceResponse,
  type IpAddressResponse,
} from './system';
export {
  fetchWifiInterfaces,
  fetchWifiInterface,
  fetchWifiClients,
  updateWifiInterface,
  updateWifiSettings,
  removeWifiClient,
  fetchWifiPassphrase,
  updateWifiPassphrase,
  scanWifiAccessPoints,
  type WifiCredentials,
  type WifiInterfaceResponse,
  type WifiConnectedClientResponse,
  type WifiPassphraseResponse,
  type WifiAccessPointResponse,
  type UpdateWifiSettingsRequest,
} from './wifi';
export {
  fetchLogs,
  type LogsCredentials,
  type LogEntryResponse,
  type GetLogsResponse,
  type FetchLogsOptions,
  type LogSeverity,
} from './logs';
export {
  fetchDnsInfo,
  updateDnsConfig,
  type DnsCredentials,
  type DnsInfoResponse,
  type UpdateDnsRequest,
} from './dns';
export {
  fetchDhcpLeases,
  fetchDhcpClients,
  makeDhcpLeaseStatic,
  removeDhcpLease,
  type DhcpCredentials,
  type DhcpLease,
  type DhcpClient,
  type DhcpLeaseAction,
} from './dhcp';
export { fetchFirewallRules, type FirewallCredentials, type FirewallRule } from './firewall';
export {
  fetchUpdateInfo,
  checkForUpdates,
  installUpdate,
  type UpdateInfoResponse,
  type UpdateCheckResponse,
  type UpdateInstallResponse,
} from './updates';
export {
  generateDiag,
  fetchDiagStatus,
  fetchDiagReport,
  DIAG_REPORT_FILENAME,
  type DiagStatusResponse,
} from './diag';
export { fetchNetStatus, type NetStatusEntry, type NetHostType } from './net';
export { fetchHealth, type HealthResponse } from './health';
export {
  listVPNClients,
  updateVPNClient,
  addL2TPClient,
  fetchL2TPClientDetails,
  updateL2TPClient,
  deleteL2TPClient,
  fetchVPNServersStatus,
  fetchOvpnServerDetails,
  fetchPptpServerDetails,
  fetchL2tpServerDetails,
  fetchSstpServerDetails,
  fetchWireguardServerDetails,
  createOvpnServer,
  fetchOvpnServerTaskStatus,
  deleteOvpnServer,
  exportOvpnClient,
  createWireguardServer,
  updateWireguardInterface,
  deleteWireguardInterface,
  fetchWireguardDetailed,
  fetchWireguardPeers,
  createWireguardPeer,
  updateWireguardPeer,
  deleteWireguardPeer,
  createWireguardClient,
  importWireguardConfig,
  listVPNUsers,
  createVPNUser,
  updateVPNUser,
  deleteVPNUser,
  listVPNProfiles,
  fetchNasnetVpnCredentials,
  finalizeWizard,
  fetchWizardStatus,
  type NasnetVpnCredentialsResponse,
  type FinalizeWizardRequest,
  type FinalizeWizardResponse,
  type FinalizeWizardInterface,
  type FinalizeWizardL2tpClient,
  type FinalizeWizardWireGuardClient,
  type FinalizeWizardWifiAp,
  type FinalizeWizardOvpnServer,
  type FinalizeWizardOvpnUser,
  type WizardStatus,
  type VPNCredentials,
  type VPNClientResponse,
  type UpdateVPNClientRequest,
  type AddL2TPClientRequest,
  type UpdateL2TPClientRequest,
  type L2TPClientDetailsResponse,
  type VPNServersStatusResponse,
  type ServerStatusItem,
  type SingleServerStatus,
  type OvpnServerDetailsResponse,
  type PptpServerDetailsResponse,
  type L2tpServerDetailsResponse,
  type SstpServerDetailsResponse,
  type WireguardServerDetailsResponse,
  type L2TPUserSecret,
  type VpnUser,
  type CreateOvpnServerRequest,
  type CreateOvpnServerResponse,
  type OvpnServerTaskStatus,
  type CreateWireguardServerRequest,
  type CreateWireguardServerResponse,
  type UpdateWireguardInterfaceRequest,
  type WireguardPeerResponse,
  type WireguardDetailedResponse,
  type CreateWireguardPeerRequest,
  type CreateWireguardPeerResponse,
  type UpdateWireguardPeerRequest,
  type CreateWireguardClientRequest,
  type CreateWireguardClientResponse,
  type ImportWireguardConfigRequest,
  type ImportWireguardConfigResponse,
  type VPNUserResponse,
  type CreateVPNUserRequest,
  type UpdateVPNUserRequest,
  type VPNProfileResponse,
} from './vpn';
export { ApiError } from './http';
export { isAbortError } from './abort';
export { BACKEND_URL } from './config';
export { loadChatwoot, toggleChatwoot } from './chatwoot';
export { initSentry, isErrorReportingEnabled, setErrorReportingEnabled } from './sentry';

export type * from '@nasnet/mocks';
