import type { DHCPLease } from '@nasnet/core/types';

export const mockServers = [
  { id: 'server-1', name: 'LAN DHCP', interface: 'bridge-lan' },
  { id: 'server-2', name: 'Guest DHCP', interface: 'bridge-guest' },
];

export const mockLeases: DHCPLease[] = [
  {
    id: 'lease-1',
    address: '192.168.1.100',
    macAddress: '00:11:22:33:44:55',
    server: 'LAN DHCP',
    status: 'bound',
    hostname: 'laptop-work',
    expiresAfter: '2h30m',
    lastSeen: '2024-01-15T10:30:00Z',
    activeAddress: '192.168.1.100',
    activeClientId: 'client-1',
    activeServer: 'LAN DHCP',
    radius: false,
    dynamic: true,
    blocked: false,
    disabled: false,
  },
  {
    id: 'lease-2',
    address: '192.168.1.101',
    macAddress: '00:11:22:33:44:56',
    server: 'LAN DHCP',
    status: 'waiting',
    hostname: 'phone-android',
    expiresAfter: '1h15m',
    lastSeen: '2024-01-15T09:00:00Z',
    activeAddress: undefined,
    activeClientId: undefined,
    activeServer: undefined,
    radius: false,
    dynamic: true,
    blocked: false,
    disabled: false,
  },
  {
    id: 'lease-3',
    address: '192.168.1.50',
    macAddress: '00:11:22:33:44:57',
    server: 'LAN DHCP',
    status: 'bound',
    hostname: 'printer-hp',
    expiresAfter: 'never',
    lastSeen: '2024-01-15T10:25:00Z',
    activeAddress: '192.168.1.50',
    activeClientId: 'client-3',
    activeServer: 'LAN DHCP',
    radius: false,
    dynamic: false,
    blocked: false,
    disabled: false,
  },
  {
    id: 'lease-4',
    address: '192.168.2.100',
    macAddress: '00:11:22:33:44:58',
    server: 'Guest DHCP',
    status: 'bound',
    hostname: 'guest-device',
    expiresAfter: '4h',
    lastSeen: '2024-01-15T10:20:00Z',
    activeAddress: '192.168.2.100',
    activeClientId: 'client-4',
    activeServer: 'Guest DHCP',
    radius: false,
    dynamic: true,
    blocked: false,
    disabled: false,
  },
  {
    id: 'lease-5',
    address: '192.168.1.102',
    macAddress: '00:11:22:33:44:59',
    server: 'LAN DHCP',
    status: 'bound',
    hostname: undefined,
    expiresAfter: '3h',
    lastSeen: '2024-01-15T10:15:00Z',
    activeAddress: '192.168.1.102',
    activeClientId: 'client-5',
    activeServer: 'LAN DHCP',
    radius: false,
    dynamic: true,
    blocked: false,
    disabled: false,
  },
  {
    id: 'lease-6',
    address: '192.168.1.103',
    macAddress: '00:11:22:33:44:60',
    server: 'LAN DHCP',
    status: 'bound',
    hostname: 'blocked-device',
    expiresAfter: '1h',
    lastSeen: '2024-01-15T10:10:00Z',
    activeAddress: '192.168.1.103',
    activeClientId: 'client-6',
    activeServer: 'LAN DHCP',
    radius: false,
    dynamic: true,
    blocked: true,
    disabled: false,
  },
];

export const createMockLease = (overrides?: Partial<DHCPLease>): DHCPLease => ({
  id: 'lease-mock',
  address: '192.168.1.200',
  macAddress: '00:AA:BB:CC:DD:EE',
  server: 'LAN DHCP',
  status: 'bound',
  hostname: 'mock-device',
  expiresAfter: '2h',
  lastSeen: new Date().toISOString(),
  activeAddress: '192.168.1.200',
  activeClientId: 'client-mock',
  activeServer: 'LAN DHCP',
  radius: false,
  dynamic: true,
  blocked: false,
  disabled: false,
  ...overrides,
});
