// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/alertdigestentry"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AlertDigestEntryCreate is the builder for creating a AlertDigestEntry entity.
type AlertDigestEntryCreate struct {
	config
	mutation *AlertDigestEntryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAlertID sets the "alert_id" field.
func (_c *AlertDigestEntryCreate) SetAlertID(v string) *AlertDigestEntryCreate {
	_c.mutation.SetAlertID(v)
	return _c
}

// SetNillableAlertID sets the "alert_id" field if the given value is not nil.
func (_c *AlertDigestEntryCreate) SetNillableAlertID(v *string) *AlertDigestEntryCreate {
	if v != nil {
		_c.SetAlertID(*v)
	}
	return _c
}

// SetRuleID sets the "rule_id" field.
func (_c *AlertDigestEntryCreate) SetRuleID(v string) *AlertDigestEntryCreate {
	_c.mutation.SetRuleID(v)
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *AlertDigestEntryCreate) SetChannelID(v string) *AlertDigestEntryCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetChannelType sets the "channel_type" field.
func (_c *AlertDigestEntryCreate) SetChannelType(v string) *AlertDigestEntryCreate {
	_c.mutation.SetChannelType(v)
	return _c
}

// SetSeverity sets the "severity" field.
func (_c *AlertDigestEntryCreate) SetSeverity(v alertdigestentry.Severity) *AlertDigestEntryCreate {
	_c.mutation.SetSeverity(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *AlertDigestEntryCreate) SetEventType(v string) *AlertDigestEntryCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *AlertDigestEntryCreate) SetTitle(v string) *AlertDigestEntryCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *AlertDigestEntryCreate) SetMessage(v string) *AlertDigestEntryCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetData sets the "data" field.
func (_c *AlertDigestEntryCreate) SetData(v map[string]interface{}) *AlertDigestEntryCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetQueuedAt sets the "queued_at" field.
func (_c *AlertDigestEntryCreate) SetQueuedAt(v time.Time) *AlertDigestEntryCreate {
	_c.mutation.SetQueuedAt(v)
	return _c
}

// SetNillableQueuedAt sets the "queued_at" field if the given value is not nil.
func (_c *AlertDigestEntryCreate) SetNillableQueuedAt(v *time.Time) *AlertDigestEntryCreate {
	if v != nil {
		_c.SetQueuedAt(*v)
	}
	return _c
}

// SetDeliveredAt sets the "delivered_at" field.
func (_c *AlertDigestEntryCreate) SetDeliveredAt(v time.Time) *AlertDigestEntryCreate {
	_c.mutation.SetDeliveredAt(v)
	return _c
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_c *AlertDigestEntryCreate) SetNillableDeliveredAt(v *time.Time) *AlertDigestEntryCreate {
	if v != nil {
		_c.SetDeliveredAt(*v)
	}
	return _c
}

// SetDigestID sets the "digest_id" field.
func (_c *AlertDigestEntryCreate) SetDigestID(v string) *AlertDigestEntryCreate {
	_c.mutation.SetDigestID(v)
	return _c
}

// SetNillableDigestID sets the "digest_id" field if the given value is not nil.
func (_c *AlertDigestEntryCreate) SetNillableDigestID(v *string) *AlertDigestEntryCreate {
	if v != nil {
		_c.SetDigestID(*v)
	}
	return _c
}

// SetBypassSent sets the "bypass_sent" field.
func (_c *AlertDigestEntryCreate) SetBypassSent(v bool) *AlertDigestEntryCreate {
	_c.mutation.SetBypassSent(v)
	return _c
}

// SetNillableBypassSent sets the "bypass_sent" field if the given value is not nil.
func (_c *AlertDigestEntryCreate) SetNillableBypassSent(v *bool) *AlertDigestEntryCreate {
	if v != nil {
		_c.SetBypassSent(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AlertDigestEntryCreate) SetID(v uuid.UUID) *AlertDigestEntryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AlertDigestEntryCreate) SetNillableID(v *uuid.UUID) *AlertDigestEntryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AlertDigestEntryMutation object of the builder.
func (_c *AlertDigestEntryCreate) Mutation() *AlertDigestEntryMutation {
	return _c.mutation
}

// Save creates the AlertDigestEntry in the database.
func (_c *AlertDigestEntryCreate) Save(ctx context.Context) (*AlertDigestEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AlertDigestEntryCreate) SaveX(ctx context.Context) *AlertDigestEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AlertDigestEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AlertDigestEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AlertDigestEntryCreate) defaults() {
	if _, ok := _c.mutation.QueuedAt(); !ok {
		v := alertdigestentry.DefaultQueuedAt()
		_c.mutation.SetQueuedAt(v)
	}
	if _, ok := _c.mutation.BypassSent(); !ok {
		v := alertdigestentry.DefaultBypassSent
		_c.mutation.SetBypassSent(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := alertdigestentry.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AlertDigestEntryCreate) check() error {
	if _, ok := _c.mutation.RuleID(); !ok {
		return &ValidationError{Name: "rule_id", err: errors.New(`ent: missing required field "AlertDigestEntry.rule_id"`)}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "AlertDigestEntry.channel_id"`)}
	}
	if _, ok := _c.mutation.ChannelType(); !ok {
		return &ValidationError{Name: "channel_type", err: errors.New(`ent: missing required field "AlertDigestEntry.channel_type"`)}
	}
	if _, ok := _c.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "AlertDigestEntry.severity"`)}
	}
	if v, ok := _c.mutation.Severity(); ok {
		if err := alertdigestentry.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "AlertDigestEntry.severity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "AlertDigestEntry.event_type"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "AlertDigestEntry.title"`)}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "AlertDigestEntry.message"`)}
	}
	if _, ok := _c.mutation.QueuedAt(); !ok {
		return &ValidationError{Name: "queued_at", err: errors.New(`ent: missing required field "AlertDigestEntry.queued_at"`)}
	}
	if _, ok := _c.mutation.BypassSent(); !ok {
		return &ValidationError{Name: "bypass_sent", err: errors.New(`ent: missing required field "AlertDigestEntry.bypass_sent"`)}
	}
	return nil
}

func (_c *AlertDigestEntryCreate) sqlSave(ctx context.Context) (*AlertDigestEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AlertDigestEntryCreate) createSpec() (*AlertDigestEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &AlertDigestEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(alertdigestentry.Table, sqlgraph.NewFieldSpec(alertdigestentry.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.AlertDigestEntry
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.AlertID(); ok {
		_spec.SetField(alertdigestentry.FieldAlertID, field.TypeString, value)
		_node.AlertID = &value
	}
	if value, ok := _c.mutation.RuleID(); ok {
		_spec.SetField(alertdigestentry.FieldRuleID, field.TypeString, value)
		_node.RuleID = value
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(alertdigestentry.FieldChannelID, field.TypeString, value)
		_node.ChannelID = value
	}
	if value, ok := _c.mutation.ChannelType(); ok {
		_spec.SetField(alertdigestentry.FieldChannelType, field.TypeString, value)
		_node.ChannelType = value
	}
	if value, ok := _c.mutation.Severity(); ok {
		_spec.SetField(alertdigestentry.FieldSeverity, field.TypeEnum, value)
		_node.Severity = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(alertdigestentry.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(alertdigestentry.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(alertdigestentry.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(alertdigestentry.FieldData, field.TypeJSON, value)
		_node.Data = value
	}
	if value, ok := _c.mutation.QueuedAt(); ok {
		_spec.SetField(alertdigestentry.FieldQueuedAt, field.TypeTime, value)
		_node.QueuedAt = value
	}
	if value, ok := _c.mutation.DeliveredAt(); ok {
		_spec.SetField(alertdigestentry.FieldDeliveredAt, field.TypeTime, value)
		_node.DeliveredAt = &value
	}
	if value, ok := _c.mutation.DigestID(); ok {
		_spec.SetField(alertdigestentry.FieldDigestID, field.TypeString, value)
		_node.DigestID = value
	}
	if value, ok := _c.mutation.BypassSent(); ok {
		_spec.SetField(alertdigestentry.FieldBypassSent, field.TypeBool, value)
		_node.BypassSent = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AlertDigestEntry.Create().
//		SetAlertID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AlertDigestEntryUpsert) {
//			SetAlertID(v+v).
//		}).
//		Exec(ctx)
func (_c *AlertDigestEntryCreate) OnConflict(opts ...sql.ConflictOption) *AlertDigestEntryUpsertOne {
	_c.conflict = opts
	return &AlertDigestEntryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AlertDigestEntry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AlertDigestEntryCreate) OnConflictColumns(columns ...string) *AlertDigestEntryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AlertDigestEntryUpsertOne{
		create: _c,
	}
}

type (
	// AlertDigestEntryUpsertOne is the builder for "upsert"-ing
	//  one AlertDigestEntry node.
	AlertDigestEntryUpsertOne struct {
		create *AlertDigestEntryCreate
	}

	// AlertDigestEntryUpsert is the "OnConflict" setter.
	AlertDigestEntryUpsert struct {
		*sql.UpdateSet
	}
)

// SetAlertID sets the "alert_id" field.
func (u *AlertDigestEntryUpsert) SetAlertID(v string) *AlertDigestEntryUpsert {
	u.Set(alertdigestentry.FieldAlertID, v)
	return u
}

// UpdateAlertID sets the "alert_id" field to the value that was provided on create.
func (u *AlertDigestEntryUpsert) UpdateAlertID() *AlertDigestEntryUpsert {
	u.SetExcluded(alertdigestentry.FieldAlertID)
	return u
}

// ClearAlertID clears the value of the "alert_id" field.
func (u *AlertDigestEntryUpsert) ClearAlertID() *AlertDigestEntryUpsert {
	u.SetNull(alertdigestentry.FieldAlertID)
	return u
}

// SetRuleID sets the "rule_id" field.
func (u *AlertDigestEntryUpsert) SetRuleID(v string) *AlertDigestEntryUpsert {
	u.Set(alertdigestentry.FieldRuleID, v)
	return u
}

// UpdateRuleID sets the "rule_id" field to the value that was provided on create.
func (u *AlertDigestEntryUpsert) UpdateRuleID() *AlertDigestEntryUpsert {
	u.SetExcluded(alertdigestentry.FieldRuleID)
	return u
}

// SetChannelID sets the "channel_id" field.
func (u *AlertDigestEntryUpsert) SetChannelID(v string) *AlertDigestEntryUpsert {
	u.Set(alertdigestentry.FieldChannelID, v)
	return u
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *AlertDigestEntryUpsert) UpdateChannelID() *AlertDigestEntryUpsert {
	u.SetExcluded(alertdigestentry.FieldChannelID)
	return u
}

// SetChannelType sets the "channel_type" field.
func (u *AlertDigestEntryUpsert) SetChannelType(v string) *AlertDigestEntryUpsert {
	u.Set(alertdigestentry.FieldChannelType, v)
	return u
}

// UpdateChannelType sets the "channel_type" field to the value that was provided on create.
func (u *AlertDigestEntryUpsert) UpdateChannelType() *AlertDigestEntryUpsert {
	u.SetExcluded(alertdigestentry.FieldChannelType)
	return u
}

// SetSeverity sets the "severity" field.
func (u *AlertDigestEntryUpsert) SetSeverity(v alertdigestentry.Severity) *AlertDigestEntryUpsert {
	u.Set(alertdigestentry.FieldSeverity, v)
	return u
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *AlertDigestEntryUpsert) UpdateSeverity() *AlertDigestEntryUpsert {
	u.SetExcluded(alertdigestentry.FieldSeverity)
	return u
}

// SetEventType sets the "event_type" field.
func (u *AlertDigestEntryUpsert) SetEventType(v string) *AlertDigestEntryUpsert {
	u.Set(alertdigestentry.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *AlertDigestEntryUpsert) UpdateEventType() *AlertDigestEntryUpsert {
	u.SetExcluded(alertdigestentry.FieldEventType)
	return u
}

// SetTitle sets the "title" field.
func (u *AlertDigestEntryUpsert) SetTitle(v string) *AlertDigestEntryUpsert {
	u.Set(alertdigestentry.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *AlertDigestEntryUpsert) UpdateTitle() *AlertDigestEntryUpsert {
	u.SetExcluded(alertdigestentry.FieldTitle)
	return u
}

// SetMessage sets the "message" field.
func (u *AlertDigestEntryUpsert) SetMessage(v string) *AlertDigestEntryUpsert {
	u.Set(alertdigestentry.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *AlertDigestEntryUpsert) UpdateMessage() *AlertDigestEntryUpsert {
	u.SetExcluded(alertdigestentry.FieldMessage)
	return u
}

// SetData sets the "data" field.
func (u *AlertDigestEntryUpsert) SetData(v map[string]interface{}) *AlertDigestEntryUpsert {
	u.Set(alertdigestentry.FieldData, v)
	return u
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *AlertDigestEntryUpsert) UpdateData() *AlertDigestEntryUpsert {
	u.SetExcluded(alertdigestentry.FieldData)
	return u
}

// ClearData clears the value of the "data" field.
func (u *AlertDigestEntryUpsert) ClearData() *AlertDigestEntryUpsert {
	u.SetNull(alertdigestentry.FieldData)
	return u
}

// SetDeliveredAt sets the "delivered_at" field.
func (u *AlertDigestEntryUpsert) SetDeliveredAt(v time.Time) *AlertDigestEntryUpsert {
	u.Set(alertdigestentry.FieldDeliveredAt, v)
	return u
}

// UpdateDeliveredAt sets the "delivered_at" field to the value that was provided on create.
func (u *AlertDigestEntryUpsert) UpdateDeliveredAt() *AlertDigestEntryUpsert {
	u.SetExcluded(alertdigestentry.FieldDeliveredAt)
	return u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (u *AlertDigestEntryUpsert) ClearDeliveredAt() *AlertDigestEntryUpsert {
	u.SetNull(alertdigestentry.FieldDeliveredAt)
	return u
}

// SetDigestID sets the "digest_id" field.
func (u *AlertDigestEntryUpsert) SetDigestID(v string) *AlertDigestEntryUpsert {
	u.Set(alertdigestentry.FieldDigestID, v)
	return u
}

// UpdateDigestID sets the "digest_id" field to the value that was provided on create.
func (u *AlertDigestEntryUpsert) UpdateDigestID() *AlertDigestEntryUpsert {
	u.SetExcluded(alertdigestentry.FieldDigestID)
	return u
}

// ClearDigestID clears the value of the "digest_id" field.
func (u *AlertDigestEntryUpsert) ClearDigestID() *AlertDigestEntryUpsert {
	u.SetNull(alertdigestentry.FieldDigestID)
	return u
}

// SetBypassSent sets the "bypass_sent" field.
func (u *AlertDigestEntryUpsert) SetBypassSent(v bool) *AlertDigestEntryUpsert {
	u.Set(alertdigestentry.FieldBypassSent, v)
	return u
}

// UpdateBypassSent sets the "bypass_sent" field to the value that was provided on create.
func (u *AlertDigestEntryUpsert) UpdateBypassSent() *AlertDigestEntryUpsert {
	u.SetExcluded(alertdigestentry.FieldBypassSent)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AlertDigestEntry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(alertdigestentry.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AlertDigestEntryUpsertOne) UpdateNewValues() *AlertDigestEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(alertdigestentry.FieldID)
		}
		if _, exists := u.create.mutation.QueuedAt(); exists {
			s.SetIgnore(alertdigestentry.FieldQueuedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AlertDigestEntry.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AlertDigestEntryUpsertOne) Ignore() *AlertDigestEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AlertDigestEntryUpsertOne) DoNothing() *AlertDigestEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AlertDigestEntryCreate.OnConflict
// documentation for more info.
func (u *AlertDigestEntryUpsertOne) Update(set func(*AlertDigestEntryUpsert)) *AlertDigestEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AlertDigestEntryUpsert{UpdateSet: update})
	}))
	return u
}

// SetAlertID sets the "alert_id" field.
func (u *AlertDigestEntryUpsertOne) SetAlertID(v string) *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetAlertID(v)
	})
}

// UpdateAlertID sets the "alert_id" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertOne) UpdateAlertID() *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateAlertID()
	})
}

// ClearAlertID clears the value of the "alert_id" field.
func (u *AlertDigestEntryUpsertOne) ClearAlertID() *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.ClearAlertID()
	})
}

// SetRuleID sets the "rule_id" field.
func (u *AlertDigestEntryUpsertOne) SetRuleID(v string) *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetRuleID(v)
	})
}

// UpdateRuleID sets the "rule_id" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertOne) UpdateRuleID() *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateRuleID()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *AlertDigestEntryUpsertOne) SetChannelID(v string) *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertOne) UpdateChannelID() *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateChannelID()
	})
}

// SetChannelType sets the "channel_type" field.
func (u *AlertDigestEntryUpsertOne) SetChannelType(v string) *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetChannelType(v)
	})
}

// UpdateChannelType sets the "channel_type" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertOne) UpdateChannelType() *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateChannelType()
	})
}

// SetSeverity sets the "severity" field.
func (u *AlertDigestEntryUpsertOne) SetSeverity(v alertdigestentry.Severity) *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetSeverity(v)
	})
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertOne) UpdateSeverity() *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateSeverity()
	})
}

// SetEventType sets the "event_type" field.
func (u *AlertDigestEntryUpsertOne) SetEventType(v string) *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertOne) UpdateEventType() *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateEventType()
	})
}

// SetTitle sets the "title" field.
func (u *AlertDigestEntryUpsertOne) SetTitle(v string) *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertOne) UpdateTitle() *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateTitle()
	})
}

// SetMessage sets the "message" field.
func (u *AlertDigestEntryUpsertOne) SetMessage(v string) *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertOne) UpdateMessage() *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateMessage()
	})
}

// SetData sets the "data" field.
func (u *AlertDigestEntryUpsertOne) SetData(v map[string]interface{}) *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertOne) UpdateData() *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateData()
	})
}

// ClearData clears the value of the "data" field.
func (u *AlertDigestEntryUpsertOne) ClearData() *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.ClearData()
	})
}

// SetDeliveredAt sets the "delivered_at" field.
func (u *AlertDigestEntryUpsertOne) SetDeliveredAt(v time.Time) *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetDeliveredAt(v)
	})
}

// UpdateDeliveredAt sets the "delivered_at" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertOne) UpdateDeliveredAt() *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateDeliveredAt()
	})
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (u *AlertDigestEntryUpsertOne) ClearDeliveredAt() *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.ClearDeliveredAt()
	})
}

// SetDigestID sets the "digest_id" field.
func (u *AlertDigestEntryUpsertOne) SetDigestID(v string) *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetDigestID(v)
	})
}

// UpdateDigestID sets the "digest_id" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertOne) UpdateDigestID() *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateDigestID()
	})
}

// ClearDigestID clears the value of the "digest_id" field.
func (u *AlertDigestEntryUpsertOne) ClearDigestID() *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.ClearDigestID()
	})
}

// SetBypassSent sets the "bypass_sent" field.
func (u *AlertDigestEntryUpsertOne) SetBypassSent(v bool) *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetBypassSent(v)
	})
}

// UpdateBypassSent sets the "bypass_sent" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertOne) UpdateBypassSent() *AlertDigestEntryUpsertOne {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateBypassSent()
	})
}

// Exec executes the query.
func (u *AlertDigestEntryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AlertDigestEntryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AlertDigestEntryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AlertDigestEntryUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AlertDigestEntryUpsertOne.ID is not supported by MySQL driver. Use AlertDigestEntryUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AlertDigestEntryUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AlertDigestEntryCreateBulk is the builder for creating many AlertDigestEntry entities in bulk.
type AlertDigestEntryCreateBulk struct {
	config
	err      error
	builders []*AlertDigestEntryCreate
	conflict []sql.ConflictOption
}

// Save creates the AlertDigestEntry entities in the database.
func (_c *AlertDigestEntryCreateBulk) Save(ctx context.Context) ([]*AlertDigestEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AlertDigestEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AlertDigestEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AlertDigestEntryCreateBulk) SaveX(ctx context.Context) []*AlertDigestEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AlertDigestEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AlertDigestEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AlertDigestEntry.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AlertDigestEntryUpsert) {
//			SetAlertID(v+v).
//		}).
//		Exec(ctx)
func (_c *AlertDigestEntryCreateBulk) OnConflict(opts ...sql.ConflictOption) *AlertDigestEntryUpsertBulk {
	_c.conflict = opts
	return &AlertDigestEntryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AlertDigestEntry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AlertDigestEntryCreateBulk) OnConflictColumns(columns ...string) *AlertDigestEntryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AlertDigestEntryUpsertBulk{
		create: _c,
	}
}

// AlertDigestEntryUpsertBulk is the builder for "upsert"-ing
// a bulk of AlertDigestEntry nodes.
type AlertDigestEntryUpsertBulk struct {
	create *AlertDigestEntryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AlertDigestEntry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(alertdigestentry.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AlertDigestEntryUpsertBulk) UpdateNewValues() *AlertDigestEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(alertdigestentry.FieldID)
			}
			if _, exists := b.mutation.QueuedAt(); exists {
				s.SetIgnore(alertdigestentry.FieldQueuedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AlertDigestEntry.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AlertDigestEntryUpsertBulk) Ignore() *AlertDigestEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AlertDigestEntryUpsertBulk) DoNothing() *AlertDigestEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AlertDigestEntryCreateBulk.OnConflict
// documentation for more info.
func (u *AlertDigestEntryUpsertBulk) Update(set func(*AlertDigestEntryUpsert)) *AlertDigestEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AlertDigestEntryUpsert{UpdateSet: update})
	}))
	return u
}

// SetAlertID sets the "alert_id" field.
func (u *AlertDigestEntryUpsertBulk) SetAlertID(v string) *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetAlertID(v)
	})
}

// UpdateAlertID sets the "alert_id" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertBulk) UpdateAlertID() *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateAlertID()
	})
}

// ClearAlertID clears the value of the "alert_id" field.
func (u *AlertDigestEntryUpsertBulk) ClearAlertID() *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.ClearAlertID()
	})
}

// SetRuleID sets the "rule_id" field.
func (u *AlertDigestEntryUpsertBulk) SetRuleID(v string) *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetRuleID(v)
	})
}

// UpdateRuleID sets the "rule_id" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertBulk) UpdateRuleID() *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateRuleID()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *AlertDigestEntryUpsertBulk) SetChannelID(v string) *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertBulk) UpdateChannelID() *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateChannelID()
	})
}

// SetChannelType sets the "channel_type" field.
func (u *AlertDigestEntryUpsertBulk) SetChannelType(v string) *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetChannelType(v)
	})
}

// UpdateChannelType sets the "channel_type" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertBulk) UpdateChannelType() *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateChannelType()
	})
}

// SetSeverity sets the "severity" field.
func (u *AlertDigestEntryUpsertBulk) SetSeverity(v alertdigestentry.Severity) *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetSeverity(v)
	})
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertBulk) UpdateSeverity() *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateSeverity()
	})
}

// SetEventType sets the "event_type" field.
func (u *AlertDigestEntryUpsertBulk) SetEventType(v string) *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertBulk) UpdateEventType() *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateEventType()
	})
}

// SetTitle sets the "title" field.
func (u *AlertDigestEntryUpsertBulk) SetTitle(v string) *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertBulk) UpdateTitle() *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateTitle()
	})
}

// SetMessage sets the "message" field.
func (u *AlertDigestEntryUpsertBulk) SetMessage(v string) *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertBulk) UpdateMessage() *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateMessage()
	})
}

// SetData sets the "data" field.
func (u *AlertDigestEntryUpsertBulk) SetData(v map[string]interface{}) *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertBulk) UpdateData() *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateData()
	})
}

// ClearData clears the value of the "data" field.
func (u *AlertDigestEntryUpsertBulk) ClearData() *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.ClearData()
	})
}

// SetDeliveredAt sets the "delivered_at" field.
func (u *AlertDigestEntryUpsertBulk) SetDeliveredAt(v time.Time) *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetDeliveredAt(v)
	})
}

// UpdateDeliveredAt sets the "delivered_at" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertBulk) UpdateDeliveredAt() *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateDeliveredAt()
	})
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (u *AlertDigestEntryUpsertBulk) ClearDeliveredAt() *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.ClearDeliveredAt()
	})
}

// SetDigestID sets the "digest_id" field.
func (u *AlertDigestEntryUpsertBulk) SetDigestID(v string) *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetDigestID(v)
	})
}

// UpdateDigestID sets the "digest_id" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertBulk) UpdateDigestID() *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateDigestID()
	})
}

// ClearDigestID clears the value of the "digest_id" field.
func (u *AlertDigestEntryUpsertBulk) ClearDigestID() *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.ClearDigestID()
	})
}

// SetBypassSent sets the "bypass_sent" field.
func (u *AlertDigestEntryUpsertBulk) SetBypassSent(v bool) *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.SetBypassSent(v)
	})
}

// UpdateBypassSent sets the "bypass_sent" field to the value that was provided on create.
func (u *AlertDigestEntryUpsertBulk) UpdateBypassSent() *AlertDigestEntryUpsertBulk {
	return u.Update(func(s *AlertDigestEntryUpsert) {
		s.UpdateBypassSent()
	})
}

// Exec executes the query.
func (u *AlertDigestEntryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AlertDigestEntryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AlertDigestEntryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AlertDigestEntryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
