// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/portknocksequence"
	"backend/ent/router"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PortKnockSequenceCreate is the builder for creating a PortKnockSequence entity.
type PortKnockSequenceCreate struct {
	config
	mutation *PortKnockSequenceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *PortKnockSequenceCreate) SetName(v string) *PortKnockSequenceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetKnockPorts sets the "knock_ports" field.
func (_c *PortKnockSequenceCreate) SetKnockPorts(v []map[string]interface{}) *PortKnockSequenceCreate {
	_c.mutation.SetKnockPorts(v)
	return _c
}

// SetProtectedPort sets the "protected_port" field.
func (_c *PortKnockSequenceCreate) SetProtectedPort(v int) *PortKnockSequenceCreate {
	_c.mutation.SetProtectedPort(v)
	return _c
}

// SetProtectedProtocol sets the "protected_protocol" field.
func (_c *PortKnockSequenceCreate) SetProtectedProtocol(v portknocksequence.ProtectedProtocol) *PortKnockSequenceCreate {
	_c.mutation.SetProtectedProtocol(v)
	return _c
}

// SetNillableProtectedProtocol sets the "protected_protocol" field if the given value is not nil.
func (_c *PortKnockSequenceCreate) SetNillableProtectedProtocol(v *portknocksequence.ProtectedProtocol) *PortKnockSequenceCreate {
	if v != nil {
		_c.SetProtectedProtocol(*v)
	}
	return _c
}

// SetAccessTimeout sets the "access_timeout" field.
func (_c *PortKnockSequenceCreate) SetAccessTimeout(v string) *PortKnockSequenceCreate {
	_c.mutation.SetAccessTimeout(v)
	return _c
}

// SetKnockTimeout sets the "knock_timeout" field.
func (_c *PortKnockSequenceCreate) SetKnockTimeout(v string) *PortKnockSequenceCreate {
	_c.mutation.SetKnockTimeout(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *PortKnockSequenceCreate) SetEnabled(v bool) *PortKnockSequenceCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *PortKnockSequenceCreate) SetNillableEnabled(v *bool) *PortKnockSequenceCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetRouterID sets the "router_id" field.
func (_c *PortKnockSequenceCreate) SetRouterID(v string) *PortKnockSequenceCreate {
	_c.mutation.SetRouterID(v)
	return _c
}

// SetGeneratedRuleIds sets the "generated_rule_ids" field.
func (_c *PortKnockSequenceCreate) SetGeneratedRuleIds(v []string) *PortKnockSequenceCreate {
	_c.mutation.SetGeneratedRuleIds(v)
	return _c
}

// SetRecentAccessCount sets the "recent_access_count" field.
func (_c *PortKnockSequenceCreate) SetRecentAccessCount(v int) *PortKnockSequenceCreate {
	_c.mutation.SetRecentAccessCount(v)
	return _c
}

// SetNillableRecentAccessCount sets the "recent_access_count" field if the given value is not nil.
func (_c *PortKnockSequenceCreate) SetNillableRecentAccessCount(v *int) *PortKnockSequenceCreate {
	if v != nil {
		_c.SetRecentAccessCount(*v)
	}
	return _c
}

// SetLastAccessedAt sets the "last_accessed_at" field.
func (_c *PortKnockSequenceCreate) SetLastAccessedAt(v time.Time) *PortKnockSequenceCreate {
	_c.mutation.SetLastAccessedAt(v)
	return _c
}

// SetNillableLastAccessedAt sets the "last_accessed_at" field if the given value is not nil.
func (_c *PortKnockSequenceCreate) SetNillableLastAccessedAt(v *time.Time) *PortKnockSequenceCreate {
	if v != nil {
		_c.SetLastAccessedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PortKnockSequenceCreate) SetCreatedAt(v time.Time) *PortKnockSequenceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PortKnockSequenceCreate) SetNillableCreatedAt(v *time.Time) *PortKnockSequenceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PortKnockSequenceCreate) SetUpdatedAt(v time.Time) *PortKnockSequenceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PortKnockSequenceCreate) SetNillableUpdatedAt(v *time.Time) *PortKnockSequenceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PortKnockSequenceCreate) SetID(v string) *PortKnockSequenceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetRouter sets the "router" edge to the Router entity.
func (_c *PortKnockSequenceCreate) SetRouter(v *Router) *PortKnockSequenceCreate {
	return _c.SetRouterID(v.ID)
}

// Mutation returns the PortKnockSequenceMutation object of the builder.
func (_c *PortKnockSequenceCreate) Mutation() *PortKnockSequenceMutation {
	return _c.mutation
}

// Save creates the PortKnockSequence in the database.
func (_c *PortKnockSequenceCreate) Save(ctx context.Context) (*PortKnockSequence, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PortKnockSequenceCreate) SaveX(ctx context.Context) *PortKnockSequence {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PortKnockSequenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PortKnockSequenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PortKnockSequenceCreate) defaults() {
	if _, ok := _c.mutation.ProtectedProtocol(); !ok {
		v := portknocksequence.DefaultProtectedProtocol
		_c.mutation.SetProtectedProtocol(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := portknocksequence.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.RecentAccessCount(); !ok {
		v := portknocksequence.DefaultRecentAccessCount
		_c.mutation.SetRecentAccessCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := portknocksequence.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := portknocksequence.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PortKnockSequenceCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PortKnockSequence.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := portknocksequence.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PortKnockSequence.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KnockPorts(); !ok {
		return &ValidationError{Name: "knock_ports", err: errors.New(`ent: missing required field "PortKnockSequence.knock_ports"`)}
	}
	if _, ok := _c.mutation.ProtectedPort(); !ok {
		return &ValidationError{Name: "protected_port", err: errors.New(`ent: missing required field "PortKnockSequence.protected_port"`)}
	}
	if v, ok := _c.mutation.ProtectedPort(); ok {
		if err := portknocksequence.ProtectedPortValidator(v); err != nil {
			return &ValidationError{Name: "protected_port", err: fmt.Errorf(`ent: validator failed for field "PortKnockSequence.protected_port": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProtectedProtocol(); !ok {
		return &ValidationError{Name: "protected_protocol", err: errors.New(`ent: missing required field "PortKnockSequence.protected_protocol"`)}
	}
	if v, ok := _c.mutation.ProtectedProtocol(); ok {
		if err := portknocksequence.ProtectedProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protected_protocol", err: fmt.Errorf(`ent: validator failed for field "PortKnockSequence.protected_protocol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccessTimeout(); !ok {
		return &ValidationError{Name: "access_timeout", err: errors.New(`ent: missing required field "PortKnockSequence.access_timeout"`)}
	}
	if v, ok := _c.mutation.AccessTimeout(); ok {
		if err := portknocksequence.AccessTimeoutValidator(v); err != nil {
			return &ValidationError{Name: "access_timeout", err: fmt.Errorf(`ent: validator failed for field "PortKnockSequence.access_timeout": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KnockTimeout(); !ok {
		return &ValidationError{Name: "knock_timeout", err: errors.New(`ent: missing required field "PortKnockSequence.knock_timeout"`)}
	}
	if v, ok := _c.mutation.KnockTimeout(); ok {
		if err := portknocksequence.KnockTimeoutValidator(v); err != nil {
			return &ValidationError{Name: "knock_timeout", err: fmt.Errorf(`ent: validator failed for field "PortKnockSequence.knock_timeout": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "PortKnockSequence.enabled"`)}
	}
	if _, ok := _c.mutation.RouterID(); !ok {
		return &ValidationError{Name: "router_id", err: errors.New(`ent: missing required field "PortKnockSequence.router_id"`)}
	}
	if v, ok := _c.mutation.RouterID(); ok {
		if err := portknocksequence.RouterIDValidator(v); err != nil {
			return &ValidationError{Name: "router_id", err: fmt.Errorf(`ent: validator failed for field "PortKnockSequence.router_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PortKnockSequence.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PortKnockSequence.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := portknocksequence.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "PortKnockSequence.id": %w`, err)}
		}
	}
	if len(_c.mutation.RouterIDs()) == 0 {
		return &ValidationError{Name: "router", err: errors.New(`ent: missing required edge "PortKnockSequence.router"`)}
	}
	return nil
}

func (_c *PortKnockSequenceCreate) sqlSave(ctx context.Context) (*PortKnockSequence, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PortKnockSequence.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PortKnockSequenceCreate) createSpec() (*PortKnockSequence, *sqlgraph.CreateSpec) {
	var (
		_node = &PortKnockSequence{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(portknocksequence.Table, sqlgraph.NewFieldSpec(portknocksequence.FieldID, field.TypeString))
	)
	_spec.Schema = _c.schemaConfig.PortKnockSequence
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(portknocksequence.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.KnockPorts(); ok {
		_spec.SetField(portknocksequence.FieldKnockPorts, field.TypeJSON, value)
		_node.KnockPorts = value
	}
	if value, ok := _c.mutation.ProtectedPort(); ok {
		_spec.SetField(portknocksequence.FieldProtectedPort, field.TypeInt, value)
		_node.ProtectedPort = value
	}
	if value, ok := _c.mutation.ProtectedProtocol(); ok {
		_spec.SetField(portknocksequence.FieldProtectedProtocol, field.TypeEnum, value)
		_node.ProtectedProtocol = value
	}
	if value, ok := _c.mutation.AccessTimeout(); ok {
		_spec.SetField(portknocksequence.FieldAccessTimeout, field.TypeString, value)
		_node.AccessTimeout = value
	}
	if value, ok := _c.mutation.KnockTimeout(); ok {
		_spec.SetField(portknocksequence.FieldKnockTimeout, field.TypeString, value)
		_node.KnockTimeout = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(portknocksequence.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.GeneratedRuleIds(); ok {
		_spec.SetField(portknocksequence.FieldGeneratedRuleIds, field.TypeJSON, value)
		_node.GeneratedRuleIds = value
	}
	if value, ok := _c.mutation.RecentAccessCount(); ok {
		_spec.SetField(portknocksequence.FieldRecentAccessCount, field.TypeInt, value)
		_node.RecentAccessCount = value
	}
	if value, ok := _c.mutation.LastAccessedAt(); ok {
		_spec.SetField(portknocksequence.FieldLastAccessedAt, field.TypeTime, value)
		_node.LastAccessedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(portknocksequence.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(portknocksequence.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.RouterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   portknocksequence.RouterTable,
			Columns: []string{portknocksequence.RouterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(router.FieldID, field.TypeString),
			},
		}
		edge.Schema = _c.schemaConfig.PortKnockSequence
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RouterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PortKnockSequence.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PortKnockSequenceUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *PortKnockSequenceCreate) OnConflict(opts ...sql.ConflictOption) *PortKnockSequenceUpsertOne {
	_c.conflict = opts
	return &PortKnockSequenceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PortKnockSequence.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PortKnockSequenceCreate) OnConflictColumns(columns ...string) *PortKnockSequenceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PortKnockSequenceUpsertOne{
		create: _c,
	}
}

type (
	// PortKnockSequenceUpsertOne is the builder for "upsert"-ing
	//  one PortKnockSequence node.
	PortKnockSequenceUpsertOne struct {
		create *PortKnockSequenceCreate
	}

	// PortKnockSequenceUpsert is the "OnConflict" setter.
	PortKnockSequenceUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *PortKnockSequenceUpsert) SetName(v string) *PortKnockSequenceUpsert {
	u.Set(portknocksequence.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PortKnockSequenceUpsert) UpdateName() *PortKnockSequenceUpsert {
	u.SetExcluded(portknocksequence.FieldName)
	return u
}

// SetKnockPorts sets the "knock_ports" field.
func (u *PortKnockSequenceUpsert) SetKnockPorts(v []map[string]interface{}) *PortKnockSequenceUpsert {
	u.Set(portknocksequence.FieldKnockPorts, v)
	return u
}

// UpdateKnockPorts sets the "knock_ports" field to the value that was provided on create.
func (u *PortKnockSequenceUpsert) UpdateKnockPorts() *PortKnockSequenceUpsert {
	u.SetExcluded(portknocksequence.FieldKnockPorts)
	return u
}

// SetProtectedPort sets the "protected_port" field.
func (u *PortKnockSequenceUpsert) SetProtectedPort(v int) *PortKnockSequenceUpsert {
	u.Set(portknocksequence.FieldProtectedPort, v)
	return u
}

// UpdateProtectedPort sets the "protected_port" field to the value that was provided on create.
func (u *PortKnockSequenceUpsert) UpdateProtectedPort() *PortKnockSequenceUpsert {
	u.SetExcluded(portknocksequence.FieldProtectedPort)
	return u
}

// AddProtectedPort adds v to the "protected_port" field.
func (u *PortKnockSequenceUpsert) AddProtectedPort(v int) *PortKnockSequenceUpsert {
	u.Add(portknocksequence.FieldProtectedPort, v)
	return u
}

// SetProtectedProtocol sets the "protected_protocol" field.
func (u *PortKnockSequenceUpsert) SetProtectedProtocol(v portknocksequence.ProtectedProtocol) *PortKnockSequenceUpsert {
	u.Set(portknocksequence.FieldProtectedProtocol, v)
	return u
}

// UpdateProtectedProtocol sets the "protected_protocol" field to the value that was provided on create.
func (u *PortKnockSequenceUpsert) UpdateProtectedProtocol() *PortKnockSequenceUpsert {
	u.SetExcluded(portknocksequence.FieldProtectedProtocol)
	return u
}

// SetAccessTimeout sets the "access_timeout" field.
func (u *PortKnockSequenceUpsert) SetAccessTimeout(v string) *PortKnockSequenceUpsert {
	u.Set(portknocksequence.FieldAccessTimeout, v)
	return u
}

// UpdateAccessTimeout sets the "access_timeout" field to the value that was provided on create.
func (u *PortKnockSequenceUpsert) UpdateAccessTimeout() *PortKnockSequenceUpsert {
	u.SetExcluded(portknocksequence.FieldAccessTimeout)
	return u
}

// SetKnockTimeout sets the "knock_timeout" field.
func (u *PortKnockSequenceUpsert) SetKnockTimeout(v string) *PortKnockSequenceUpsert {
	u.Set(portknocksequence.FieldKnockTimeout, v)
	return u
}

// UpdateKnockTimeout sets the "knock_timeout" field to the value that was provided on create.
func (u *PortKnockSequenceUpsert) UpdateKnockTimeout() *PortKnockSequenceUpsert {
	u.SetExcluded(portknocksequence.FieldKnockTimeout)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *PortKnockSequenceUpsert) SetEnabled(v bool) *PortKnockSequenceUpsert {
	u.Set(portknocksequence.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PortKnockSequenceUpsert) UpdateEnabled() *PortKnockSequenceUpsert {
	u.SetExcluded(portknocksequence.FieldEnabled)
	return u
}

// SetRouterID sets the "router_id" field.
func (u *PortKnockSequenceUpsert) SetRouterID(v string) *PortKnockSequenceUpsert {
	u.Set(portknocksequence.FieldRouterID, v)
	return u
}

// UpdateRouterID sets the "router_id" field to the value that was provided on create.
func (u *PortKnockSequenceUpsert) UpdateRouterID() *PortKnockSequenceUpsert {
	u.SetExcluded(portknocksequence.FieldRouterID)
	return u
}

// SetGeneratedRuleIds sets the "generated_rule_ids" field.
func (u *PortKnockSequenceUpsert) SetGeneratedRuleIds(v []string) *PortKnockSequenceUpsert {
	u.Set(portknocksequence.FieldGeneratedRuleIds, v)
	return u
}

// UpdateGeneratedRuleIds sets the "generated_rule_ids" field to the value that was provided on create.
func (u *PortKnockSequenceUpsert) UpdateGeneratedRuleIds() *PortKnockSequenceUpsert {
	u.SetExcluded(portknocksequence.FieldGeneratedRuleIds)
	return u
}

// ClearGeneratedRuleIds clears the value of the "generated_rule_ids" field.
func (u *PortKnockSequenceUpsert) ClearGeneratedRuleIds() *PortKnockSequenceUpsert {
	u.SetNull(portknocksequence.FieldGeneratedRuleIds)
	return u
}

// SetRecentAccessCount sets the "recent_access_count" field.
func (u *PortKnockSequenceUpsert) SetRecentAccessCount(v int) *PortKnockSequenceUpsert {
	u.Set(portknocksequence.FieldRecentAccessCount, v)
	return u
}

// UpdateRecentAccessCount sets the "recent_access_count" field to the value that was provided on create.
func (u *PortKnockSequenceUpsert) UpdateRecentAccessCount() *PortKnockSequenceUpsert {
	u.SetExcluded(portknocksequence.FieldRecentAccessCount)
	return u
}

// AddRecentAccessCount adds v to the "recent_access_count" field.
func (u *PortKnockSequenceUpsert) AddRecentAccessCount(v int) *PortKnockSequenceUpsert {
	u.Add(portknocksequence.FieldRecentAccessCount, v)
	return u
}

// ClearRecentAccessCount clears the value of the "recent_access_count" field.
func (u *PortKnockSequenceUpsert) ClearRecentAccessCount() *PortKnockSequenceUpsert {
	u.SetNull(portknocksequence.FieldRecentAccessCount)
	return u
}

// SetLastAccessedAt sets the "last_accessed_at" field.
func (u *PortKnockSequenceUpsert) SetLastAccessedAt(v time.Time) *PortKnockSequenceUpsert {
	u.Set(portknocksequence.FieldLastAccessedAt, v)
	return u
}

// UpdateLastAccessedAt sets the "last_accessed_at" field to the value that was provided on create.
func (u *PortKnockSequenceUpsert) UpdateLastAccessedAt() *PortKnockSequenceUpsert {
	u.SetExcluded(portknocksequence.FieldLastAccessedAt)
	return u
}

// ClearLastAccessedAt clears the value of the "last_accessed_at" field.
func (u *PortKnockSequenceUpsert) ClearLastAccessedAt() *PortKnockSequenceUpsert {
	u.SetNull(portknocksequence.FieldLastAccessedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PortKnockSequenceUpsert) SetUpdatedAt(v time.Time) *PortKnockSequenceUpsert {
	u.Set(portknocksequence.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PortKnockSequenceUpsert) UpdateUpdatedAt() *PortKnockSequenceUpsert {
	u.SetExcluded(portknocksequence.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PortKnockSequence.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(portknocksequence.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PortKnockSequenceUpsertOne) UpdateNewValues() *PortKnockSequenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(portknocksequence.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(portknocksequence.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PortKnockSequence.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PortKnockSequenceUpsertOne) Ignore() *PortKnockSequenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PortKnockSequenceUpsertOne) DoNothing() *PortKnockSequenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PortKnockSequenceCreate.OnConflict
// documentation for more info.
func (u *PortKnockSequenceUpsertOne) Update(set func(*PortKnockSequenceUpsert)) *PortKnockSequenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PortKnockSequenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *PortKnockSequenceUpsertOne) SetName(v string) *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertOne) UpdateName() *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateName()
	})
}

// SetKnockPorts sets the "knock_ports" field.
func (u *PortKnockSequenceUpsertOne) SetKnockPorts(v []map[string]interface{}) *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetKnockPorts(v)
	})
}

// UpdateKnockPorts sets the "knock_ports" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertOne) UpdateKnockPorts() *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateKnockPorts()
	})
}

// SetProtectedPort sets the "protected_port" field.
func (u *PortKnockSequenceUpsertOne) SetProtectedPort(v int) *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetProtectedPort(v)
	})
}

// AddProtectedPort adds v to the "protected_port" field.
func (u *PortKnockSequenceUpsertOne) AddProtectedPort(v int) *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.AddProtectedPort(v)
	})
}

// UpdateProtectedPort sets the "protected_port" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertOne) UpdateProtectedPort() *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateProtectedPort()
	})
}

// SetProtectedProtocol sets the "protected_protocol" field.
func (u *PortKnockSequenceUpsertOne) SetProtectedProtocol(v portknocksequence.ProtectedProtocol) *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetProtectedProtocol(v)
	})
}

// UpdateProtectedProtocol sets the "protected_protocol" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertOne) UpdateProtectedProtocol() *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateProtectedProtocol()
	})
}

// SetAccessTimeout sets the "access_timeout" field.
func (u *PortKnockSequenceUpsertOne) SetAccessTimeout(v string) *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetAccessTimeout(v)
	})
}

// UpdateAccessTimeout sets the "access_timeout" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertOne) UpdateAccessTimeout() *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateAccessTimeout()
	})
}

// SetKnockTimeout sets the "knock_timeout" field.
func (u *PortKnockSequenceUpsertOne) SetKnockTimeout(v string) *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetKnockTimeout(v)
	})
}

// UpdateKnockTimeout sets the "knock_timeout" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertOne) UpdateKnockTimeout() *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateKnockTimeout()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PortKnockSequenceUpsertOne) SetEnabled(v bool) *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertOne) UpdateEnabled() *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateEnabled()
	})
}

// SetRouterID sets the "router_id" field.
func (u *PortKnockSequenceUpsertOne) SetRouterID(v string) *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetRouterID(v)
	})
}

// UpdateRouterID sets the "router_id" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertOne) UpdateRouterID() *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateRouterID()
	})
}

// SetGeneratedRuleIds sets the "generated_rule_ids" field.
func (u *PortKnockSequenceUpsertOne) SetGeneratedRuleIds(v []string) *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetGeneratedRuleIds(v)
	})
}

// UpdateGeneratedRuleIds sets the "generated_rule_ids" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertOne) UpdateGeneratedRuleIds() *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateGeneratedRuleIds()
	})
}

// ClearGeneratedRuleIds clears the value of the "generated_rule_ids" field.
func (u *PortKnockSequenceUpsertOne) ClearGeneratedRuleIds() *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.ClearGeneratedRuleIds()
	})
}

// SetRecentAccessCount sets the "recent_access_count" field.
func (u *PortKnockSequenceUpsertOne) SetRecentAccessCount(v int) *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetRecentAccessCount(v)
	})
}

// AddRecentAccessCount adds v to the "recent_access_count" field.
func (u *PortKnockSequenceUpsertOne) AddRecentAccessCount(v int) *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.AddRecentAccessCount(v)
	})
}

// UpdateRecentAccessCount sets the "recent_access_count" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertOne) UpdateRecentAccessCount() *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateRecentAccessCount()
	})
}

// ClearRecentAccessCount clears the value of the "recent_access_count" field.
func (u *PortKnockSequenceUpsertOne) ClearRecentAccessCount() *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.ClearRecentAccessCount()
	})
}

// SetLastAccessedAt sets the "last_accessed_at" field.
func (u *PortKnockSequenceUpsertOne) SetLastAccessedAt(v time.Time) *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetLastAccessedAt(v)
	})
}

// UpdateLastAccessedAt sets the "last_accessed_at" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertOne) UpdateLastAccessedAt() *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateLastAccessedAt()
	})
}

// ClearLastAccessedAt clears the value of the "last_accessed_at" field.
func (u *PortKnockSequenceUpsertOne) ClearLastAccessedAt() *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.ClearLastAccessedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PortKnockSequenceUpsertOne) SetUpdatedAt(v time.Time) *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertOne) UpdateUpdatedAt() *PortKnockSequenceUpsertOne {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PortKnockSequenceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PortKnockSequenceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PortKnockSequenceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PortKnockSequenceUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PortKnockSequenceUpsertOne.ID is not supported by MySQL driver. Use PortKnockSequenceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PortKnockSequenceUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PortKnockSequenceCreateBulk is the builder for creating many PortKnockSequence entities in bulk.
type PortKnockSequenceCreateBulk struct {
	config
	err      error
	builders []*PortKnockSequenceCreate
	conflict []sql.ConflictOption
}

// Save creates the PortKnockSequence entities in the database.
func (_c *PortKnockSequenceCreateBulk) Save(ctx context.Context) ([]*PortKnockSequence, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PortKnockSequence, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PortKnockSequenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PortKnockSequenceCreateBulk) SaveX(ctx context.Context) []*PortKnockSequence {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PortKnockSequenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PortKnockSequenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PortKnockSequence.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PortKnockSequenceUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *PortKnockSequenceCreateBulk) OnConflict(opts ...sql.ConflictOption) *PortKnockSequenceUpsertBulk {
	_c.conflict = opts
	return &PortKnockSequenceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PortKnockSequence.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PortKnockSequenceCreateBulk) OnConflictColumns(columns ...string) *PortKnockSequenceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PortKnockSequenceUpsertBulk{
		create: _c,
	}
}

// PortKnockSequenceUpsertBulk is the builder for "upsert"-ing
// a bulk of PortKnockSequence nodes.
type PortKnockSequenceUpsertBulk struct {
	create *PortKnockSequenceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PortKnockSequence.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(portknocksequence.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PortKnockSequenceUpsertBulk) UpdateNewValues() *PortKnockSequenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(portknocksequence.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(portknocksequence.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PortKnockSequence.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PortKnockSequenceUpsertBulk) Ignore() *PortKnockSequenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PortKnockSequenceUpsertBulk) DoNothing() *PortKnockSequenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PortKnockSequenceCreateBulk.OnConflict
// documentation for more info.
func (u *PortKnockSequenceUpsertBulk) Update(set func(*PortKnockSequenceUpsert)) *PortKnockSequenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PortKnockSequenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *PortKnockSequenceUpsertBulk) SetName(v string) *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertBulk) UpdateName() *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateName()
	})
}

// SetKnockPorts sets the "knock_ports" field.
func (u *PortKnockSequenceUpsertBulk) SetKnockPorts(v []map[string]interface{}) *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetKnockPorts(v)
	})
}

// UpdateKnockPorts sets the "knock_ports" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertBulk) UpdateKnockPorts() *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateKnockPorts()
	})
}

// SetProtectedPort sets the "protected_port" field.
func (u *PortKnockSequenceUpsertBulk) SetProtectedPort(v int) *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetProtectedPort(v)
	})
}

// AddProtectedPort adds v to the "protected_port" field.
func (u *PortKnockSequenceUpsertBulk) AddProtectedPort(v int) *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.AddProtectedPort(v)
	})
}

// UpdateProtectedPort sets the "protected_port" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertBulk) UpdateProtectedPort() *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateProtectedPort()
	})
}

// SetProtectedProtocol sets the "protected_protocol" field.
func (u *PortKnockSequenceUpsertBulk) SetProtectedProtocol(v portknocksequence.ProtectedProtocol) *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetProtectedProtocol(v)
	})
}

// UpdateProtectedProtocol sets the "protected_protocol" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertBulk) UpdateProtectedProtocol() *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateProtectedProtocol()
	})
}

// SetAccessTimeout sets the "access_timeout" field.
func (u *PortKnockSequenceUpsertBulk) SetAccessTimeout(v string) *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetAccessTimeout(v)
	})
}

// UpdateAccessTimeout sets the "access_timeout" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertBulk) UpdateAccessTimeout() *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateAccessTimeout()
	})
}

// SetKnockTimeout sets the "knock_timeout" field.
func (u *PortKnockSequenceUpsertBulk) SetKnockTimeout(v string) *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetKnockTimeout(v)
	})
}

// UpdateKnockTimeout sets the "knock_timeout" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertBulk) UpdateKnockTimeout() *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateKnockTimeout()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PortKnockSequenceUpsertBulk) SetEnabled(v bool) *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertBulk) UpdateEnabled() *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateEnabled()
	})
}

// SetRouterID sets the "router_id" field.
func (u *PortKnockSequenceUpsertBulk) SetRouterID(v string) *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetRouterID(v)
	})
}

// UpdateRouterID sets the "router_id" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertBulk) UpdateRouterID() *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateRouterID()
	})
}

// SetGeneratedRuleIds sets the "generated_rule_ids" field.
func (u *PortKnockSequenceUpsertBulk) SetGeneratedRuleIds(v []string) *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetGeneratedRuleIds(v)
	})
}

// UpdateGeneratedRuleIds sets the "generated_rule_ids" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertBulk) UpdateGeneratedRuleIds() *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateGeneratedRuleIds()
	})
}

// ClearGeneratedRuleIds clears the value of the "generated_rule_ids" field.
func (u *PortKnockSequenceUpsertBulk) ClearGeneratedRuleIds() *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.ClearGeneratedRuleIds()
	})
}

// SetRecentAccessCount sets the "recent_access_count" field.
func (u *PortKnockSequenceUpsertBulk) SetRecentAccessCount(v int) *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetRecentAccessCount(v)
	})
}

// AddRecentAccessCount adds v to the "recent_access_count" field.
func (u *PortKnockSequenceUpsertBulk) AddRecentAccessCount(v int) *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.AddRecentAccessCount(v)
	})
}

// UpdateRecentAccessCount sets the "recent_access_count" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertBulk) UpdateRecentAccessCount() *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateRecentAccessCount()
	})
}

// ClearRecentAccessCount clears the value of the "recent_access_count" field.
func (u *PortKnockSequenceUpsertBulk) ClearRecentAccessCount() *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.ClearRecentAccessCount()
	})
}

// SetLastAccessedAt sets the "last_accessed_at" field.
func (u *PortKnockSequenceUpsertBulk) SetLastAccessedAt(v time.Time) *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetLastAccessedAt(v)
	})
}

// UpdateLastAccessedAt sets the "last_accessed_at" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertBulk) UpdateLastAccessedAt() *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateLastAccessedAt()
	})
}

// ClearLastAccessedAt clears the value of the "last_accessed_at" field.
func (u *PortKnockSequenceUpsertBulk) ClearLastAccessedAt() *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.ClearLastAccessedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PortKnockSequenceUpsertBulk) SetUpdatedAt(v time.Time) *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PortKnockSequenceUpsertBulk) UpdateUpdatedAt() *PortKnockSequenceUpsertBulk {
	return u.Update(func(s *PortKnockSequenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PortKnockSequenceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PortKnockSequenceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PortKnockSequenceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PortKnockSequenceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
