// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/schemaversion"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SchemaVersionCreate is the builder for creating a SchemaVersion entity.
type SchemaVersionCreate struct {
	config
	mutation *SchemaVersionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetVersion sets the "version" field.
func (_c *SchemaVersionCreate) SetVersion(v int64) *SchemaVersionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SchemaVersionCreate) SetName(v string) *SchemaVersionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetChecksum sets the "checksum" field.
func (_c *SchemaVersionCreate) SetChecksum(v string) *SchemaVersionCreate {
	_c.mutation.SetChecksum(v)
	return _c
}

// SetApplied sets the "applied" field.
func (_c *SchemaVersionCreate) SetApplied(v bool) *SchemaVersionCreate {
	_c.mutation.SetApplied(v)
	return _c
}

// SetNillableApplied sets the "applied" field if the given value is not nil.
func (_c *SchemaVersionCreate) SetNillableApplied(v *bool) *SchemaVersionCreate {
	if v != nil {
		_c.SetApplied(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *SchemaVersionCreate) SetErrorMessage(v string) *SchemaVersionCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *SchemaVersionCreate) SetNillableErrorMessage(v *string) *SchemaVersionCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetExecutionTimeMs sets the "execution_time_ms" field.
func (_c *SchemaVersionCreate) SetExecutionTimeMs(v int64) *SchemaVersionCreate {
	_c.mutation.SetExecutionTimeMs(v)
	return _c
}

// SetNillableExecutionTimeMs sets the "execution_time_ms" field if the given value is not nil.
func (_c *SchemaVersionCreate) SetNillableExecutionTimeMs(v *int64) *SchemaVersionCreate {
	if v != nil {
		_c.SetExecutionTimeMs(*v)
	}
	return _c
}

// SetAppliedAt sets the "applied_at" field.
func (_c *SchemaVersionCreate) SetAppliedAt(v time.Time) *SchemaVersionCreate {
	_c.mutation.SetAppliedAt(v)
	return _c
}

// SetNillableAppliedAt sets the "applied_at" field if the given value is not nil.
func (_c *SchemaVersionCreate) SetNillableAppliedAt(v *time.Time) *SchemaVersionCreate {
	if v != nil {
		_c.SetAppliedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SchemaVersionCreate) SetID(v string) *SchemaVersionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SchemaVersionMutation object of the builder.
func (_c *SchemaVersionCreate) Mutation() *SchemaVersionMutation {
	return _c.mutation
}

// Save creates the SchemaVersion in the database.
func (_c *SchemaVersionCreate) Save(ctx context.Context) (*SchemaVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SchemaVersionCreate) SaveX(ctx context.Context) *SchemaVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SchemaVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SchemaVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SchemaVersionCreate) defaults() {
	if _, ok := _c.mutation.Applied(); !ok {
		v := schemaversion.DefaultApplied
		_c.mutation.SetApplied(v)
	}
	if _, ok := _c.mutation.AppliedAt(); !ok {
		v := schemaversion.DefaultAppliedAt()
		_c.mutation.SetAppliedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SchemaVersionCreate) check() error {
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "SchemaVersion.version"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SchemaVersion.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := schemaversion.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SchemaVersion.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Checksum(); !ok {
		return &ValidationError{Name: "checksum", err: errors.New(`ent: missing required field "SchemaVersion.checksum"`)}
	}
	if v, ok := _c.mutation.Checksum(); ok {
		if err := schemaversion.ChecksumValidator(v); err != nil {
			return &ValidationError{Name: "checksum", err: fmt.Errorf(`ent: validator failed for field "SchemaVersion.checksum": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Applied(); !ok {
		return &ValidationError{Name: "applied", err: errors.New(`ent: missing required field "SchemaVersion.applied"`)}
	}
	if v, ok := _c.mutation.ErrorMessage(); ok {
		if err := schemaversion.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "SchemaVersion.error_message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AppliedAt(); !ok {
		return &ValidationError{Name: "applied_at", err: errors.New(`ent: missing required field "SchemaVersion.applied_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := schemaversion.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SchemaVersion.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SchemaVersionCreate) sqlSave(ctx context.Context) (*SchemaVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SchemaVersion.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SchemaVersionCreate) createSpec() (*SchemaVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &SchemaVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(schemaversion.Table, sqlgraph.NewFieldSpec(schemaversion.FieldID, field.TypeString))
	)
	_spec.Schema = _c.schemaConfig.SchemaVersion
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(schemaversion.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(schemaversion.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Checksum(); ok {
		_spec.SetField(schemaversion.FieldChecksum, field.TypeString, value)
		_node.Checksum = value
	}
	if value, ok := _c.mutation.Applied(); ok {
		_spec.SetField(schemaversion.FieldApplied, field.TypeBool, value)
		_node.Applied = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(schemaversion.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.ExecutionTimeMs(); ok {
		_spec.SetField(schemaversion.FieldExecutionTimeMs, field.TypeInt64, value)
		_node.ExecutionTimeMs = value
	}
	if value, ok := _c.mutation.AppliedAt(); ok {
		_spec.SetField(schemaversion.FieldAppliedAt, field.TypeTime, value)
		_node.AppliedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SchemaVersion.Create().
//		SetVersion(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SchemaVersionUpsert) {
//			SetVersion(v+v).
//		}).
//		Exec(ctx)
func (_c *SchemaVersionCreate) OnConflict(opts ...sql.ConflictOption) *SchemaVersionUpsertOne {
	_c.conflict = opts
	return &SchemaVersionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SchemaVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SchemaVersionCreate) OnConflictColumns(columns ...string) *SchemaVersionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SchemaVersionUpsertOne{
		create: _c,
	}
}

type (
	// SchemaVersionUpsertOne is the builder for "upsert"-ing
	//  one SchemaVersion node.
	SchemaVersionUpsertOne struct {
		create *SchemaVersionCreate
	}

	// SchemaVersionUpsert is the "OnConflict" setter.
	SchemaVersionUpsert struct {
		*sql.UpdateSet
	}
)

// SetVersion sets the "version" field.
func (u *SchemaVersionUpsert) SetVersion(v int64) *SchemaVersionUpsert {
	u.Set(schemaversion.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SchemaVersionUpsert) UpdateVersion() *SchemaVersionUpsert {
	u.SetExcluded(schemaversion.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *SchemaVersionUpsert) AddVersion(v int64) *SchemaVersionUpsert {
	u.Add(schemaversion.FieldVersion, v)
	return u
}

// SetName sets the "name" field.
func (u *SchemaVersionUpsert) SetName(v string) *SchemaVersionUpsert {
	u.Set(schemaversion.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SchemaVersionUpsert) UpdateName() *SchemaVersionUpsert {
	u.SetExcluded(schemaversion.FieldName)
	return u
}

// SetChecksum sets the "checksum" field.
func (u *SchemaVersionUpsert) SetChecksum(v string) *SchemaVersionUpsert {
	u.Set(schemaversion.FieldChecksum, v)
	return u
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *SchemaVersionUpsert) UpdateChecksum() *SchemaVersionUpsert {
	u.SetExcluded(schemaversion.FieldChecksum)
	return u
}

// SetApplied sets the "applied" field.
func (u *SchemaVersionUpsert) SetApplied(v bool) *SchemaVersionUpsert {
	u.Set(schemaversion.FieldApplied, v)
	return u
}

// UpdateApplied sets the "applied" field to the value that was provided on create.
func (u *SchemaVersionUpsert) UpdateApplied() *SchemaVersionUpsert {
	u.SetExcluded(schemaversion.FieldApplied)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *SchemaVersionUpsert) SetErrorMessage(v string) *SchemaVersionUpsert {
	u.Set(schemaversion.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *SchemaVersionUpsert) UpdateErrorMessage() *SchemaVersionUpsert {
	u.SetExcluded(schemaversion.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *SchemaVersionUpsert) ClearErrorMessage() *SchemaVersionUpsert {
	u.SetNull(schemaversion.FieldErrorMessage)
	return u
}

// SetExecutionTimeMs sets the "execution_time_ms" field.
func (u *SchemaVersionUpsert) SetExecutionTimeMs(v int64) *SchemaVersionUpsert {
	u.Set(schemaversion.FieldExecutionTimeMs, v)
	return u
}

// UpdateExecutionTimeMs sets the "execution_time_ms" field to the value that was provided on create.
func (u *SchemaVersionUpsert) UpdateExecutionTimeMs() *SchemaVersionUpsert {
	u.SetExcluded(schemaversion.FieldExecutionTimeMs)
	return u
}

// AddExecutionTimeMs adds v to the "execution_time_ms" field.
func (u *SchemaVersionUpsert) AddExecutionTimeMs(v int64) *SchemaVersionUpsert {
	u.Add(schemaversion.FieldExecutionTimeMs, v)
	return u
}

// ClearExecutionTimeMs clears the value of the "execution_time_ms" field.
func (u *SchemaVersionUpsert) ClearExecutionTimeMs() *SchemaVersionUpsert {
	u.SetNull(schemaversion.FieldExecutionTimeMs)
	return u
}

// SetAppliedAt sets the "applied_at" field.
func (u *SchemaVersionUpsert) SetAppliedAt(v time.Time) *SchemaVersionUpsert {
	u.Set(schemaversion.FieldAppliedAt, v)
	return u
}

// UpdateAppliedAt sets the "applied_at" field to the value that was provided on create.
func (u *SchemaVersionUpsert) UpdateAppliedAt() *SchemaVersionUpsert {
	u.SetExcluded(schemaversion.FieldAppliedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SchemaVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(schemaversion.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SchemaVersionUpsertOne) UpdateNewValues() *SchemaVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(schemaversion.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SchemaVersion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SchemaVersionUpsertOne) Ignore() *SchemaVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SchemaVersionUpsertOne) DoNothing() *SchemaVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SchemaVersionCreate.OnConflict
// documentation for more info.
func (u *SchemaVersionUpsertOne) Update(set func(*SchemaVersionUpsert)) *SchemaVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SchemaVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetVersion sets the "version" field.
func (u *SchemaVersionUpsertOne) SetVersion(v int64) *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *SchemaVersionUpsertOne) AddVersion(v int64) *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SchemaVersionUpsertOne) UpdateVersion() *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.UpdateVersion()
	})
}

// SetName sets the "name" field.
func (u *SchemaVersionUpsertOne) SetName(v string) *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SchemaVersionUpsertOne) UpdateName() *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.UpdateName()
	})
}

// SetChecksum sets the "checksum" field.
func (u *SchemaVersionUpsertOne) SetChecksum(v string) *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.SetChecksum(v)
	})
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *SchemaVersionUpsertOne) UpdateChecksum() *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.UpdateChecksum()
	})
}

// SetApplied sets the "applied" field.
func (u *SchemaVersionUpsertOne) SetApplied(v bool) *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.SetApplied(v)
	})
}

// UpdateApplied sets the "applied" field to the value that was provided on create.
func (u *SchemaVersionUpsertOne) UpdateApplied() *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.UpdateApplied()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *SchemaVersionUpsertOne) SetErrorMessage(v string) *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *SchemaVersionUpsertOne) UpdateErrorMessage() *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *SchemaVersionUpsertOne) ClearErrorMessage() *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.ClearErrorMessage()
	})
}

// SetExecutionTimeMs sets the "execution_time_ms" field.
func (u *SchemaVersionUpsertOne) SetExecutionTimeMs(v int64) *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.SetExecutionTimeMs(v)
	})
}

// AddExecutionTimeMs adds v to the "execution_time_ms" field.
func (u *SchemaVersionUpsertOne) AddExecutionTimeMs(v int64) *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.AddExecutionTimeMs(v)
	})
}

// UpdateExecutionTimeMs sets the "execution_time_ms" field to the value that was provided on create.
func (u *SchemaVersionUpsertOne) UpdateExecutionTimeMs() *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.UpdateExecutionTimeMs()
	})
}

// ClearExecutionTimeMs clears the value of the "execution_time_ms" field.
func (u *SchemaVersionUpsertOne) ClearExecutionTimeMs() *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.ClearExecutionTimeMs()
	})
}

// SetAppliedAt sets the "applied_at" field.
func (u *SchemaVersionUpsertOne) SetAppliedAt(v time.Time) *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.SetAppliedAt(v)
	})
}

// UpdateAppliedAt sets the "applied_at" field to the value that was provided on create.
func (u *SchemaVersionUpsertOne) UpdateAppliedAt() *SchemaVersionUpsertOne {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.UpdateAppliedAt()
	})
}

// Exec executes the query.
func (u *SchemaVersionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SchemaVersionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SchemaVersionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SchemaVersionUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SchemaVersionUpsertOne.ID is not supported by MySQL driver. Use SchemaVersionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SchemaVersionUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SchemaVersionCreateBulk is the builder for creating many SchemaVersion entities in bulk.
type SchemaVersionCreateBulk struct {
	config
	err      error
	builders []*SchemaVersionCreate
	conflict []sql.ConflictOption
}

// Save creates the SchemaVersion entities in the database.
func (_c *SchemaVersionCreateBulk) Save(ctx context.Context) ([]*SchemaVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SchemaVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SchemaVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SchemaVersionCreateBulk) SaveX(ctx context.Context) []*SchemaVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SchemaVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SchemaVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SchemaVersion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SchemaVersionUpsert) {
//			SetVersion(v+v).
//		}).
//		Exec(ctx)
func (_c *SchemaVersionCreateBulk) OnConflict(opts ...sql.ConflictOption) *SchemaVersionUpsertBulk {
	_c.conflict = opts
	return &SchemaVersionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SchemaVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SchemaVersionCreateBulk) OnConflictColumns(columns ...string) *SchemaVersionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SchemaVersionUpsertBulk{
		create: _c,
	}
}

// SchemaVersionUpsertBulk is the builder for "upsert"-ing
// a bulk of SchemaVersion nodes.
type SchemaVersionUpsertBulk struct {
	create *SchemaVersionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SchemaVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(schemaversion.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SchemaVersionUpsertBulk) UpdateNewValues() *SchemaVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(schemaversion.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SchemaVersion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SchemaVersionUpsertBulk) Ignore() *SchemaVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SchemaVersionUpsertBulk) DoNothing() *SchemaVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SchemaVersionCreateBulk.OnConflict
// documentation for more info.
func (u *SchemaVersionUpsertBulk) Update(set func(*SchemaVersionUpsert)) *SchemaVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SchemaVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetVersion sets the "version" field.
func (u *SchemaVersionUpsertBulk) SetVersion(v int64) *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *SchemaVersionUpsertBulk) AddVersion(v int64) *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SchemaVersionUpsertBulk) UpdateVersion() *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.UpdateVersion()
	})
}

// SetName sets the "name" field.
func (u *SchemaVersionUpsertBulk) SetName(v string) *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SchemaVersionUpsertBulk) UpdateName() *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.UpdateName()
	})
}

// SetChecksum sets the "checksum" field.
func (u *SchemaVersionUpsertBulk) SetChecksum(v string) *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.SetChecksum(v)
	})
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *SchemaVersionUpsertBulk) UpdateChecksum() *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.UpdateChecksum()
	})
}

// SetApplied sets the "applied" field.
func (u *SchemaVersionUpsertBulk) SetApplied(v bool) *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.SetApplied(v)
	})
}

// UpdateApplied sets the "applied" field to the value that was provided on create.
func (u *SchemaVersionUpsertBulk) UpdateApplied() *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.UpdateApplied()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *SchemaVersionUpsertBulk) SetErrorMessage(v string) *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *SchemaVersionUpsertBulk) UpdateErrorMessage() *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *SchemaVersionUpsertBulk) ClearErrorMessage() *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.ClearErrorMessage()
	})
}

// SetExecutionTimeMs sets the "execution_time_ms" field.
func (u *SchemaVersionUpsertBulk) SetExecutionTimeMs(v int64) *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.SetExecutionTimeMs(v)
	})
}

// AddExecutionTimeMs adds v to the "execution_time_ms" field.
func (u *SchemaVersionUpsertBulk) AddExecutionTimeMs(v int64) *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.AddExecutionTimeMs(v)
	})
}

// UpdateExecutionTimeMs sets the "execution_time_ms" field to the value that was provided on create.
func (u *SchemaVersionUpsertBulk) UpdateExecutionTimeMs() *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.UpdateExecutionTimeMs()
	})
}

// ClearExecutionTimeMs clears the value of the "execution_time_ms" field.
func (u *SchemaVersionUpsertBulk) ClearExecutionTimeMs() *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.ClearExecutionTimeMs()
	})
}

// SetAppliedAt sets the "applied_at" field.
func (u *SchemaVersionUpsertBulk) SetAppliedAt(v time.Time) *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.SetAppliedAt(v)
	})
}

// UpdateAppliedAt sets the "applied_at" field to the value that was provided on create.
func (u *SchemaVersionUpsertBulk) UpdateAppliedAt() *SchemaVersionUpsertBulk {
	return u.Update(func(s *SchemaVersionUpsert) {
		s.UpdateAppliedAt()
	})
}

// Exec executes the query.
func (u *SchemaVersionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SchemaVersionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SchemaVersionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SchemaVersionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
