// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/router"
	"backend/ent/serviceinstance"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ServiceInstance is the model entity for the ServiceInstance schema.
type ServiceInstance struct {
	config `json:"-"`
	// ID of the ent.
	// ULID primary key
	ID string `json:"id,omitempty"`
	// Feature identifier (e.g., 'tor', 'sing-box', 'xray-core')
	FeatureID string `json:"feature_id,omitempty"`
	// Human-readable instance name
	InstanceName string `json:"instance_name,omitempty"`
	// Router ID this instance belongs to
	RouterID string `json:"router_id,omitempty"`
	// Current instance lifecycle status
	Status serviceinstance.Status `json:"status,omitempty"`
	// VLAN ID for network isolation (optional)
	VlanID *int `json:"vlan_id,omitempty"`
	// IP address to bind the service to (optional)
	BindIP string `json:"bind_ip,omitempty"`
	// List of ports used by this service instance
	Ports []int `json:"ports,omitempty"`
	// Service-specific configuration (JSON)
	Config map[string]interface{} `json:"config,omitempty"`
	// Path to the service binary on the router filesystem
	BinaryPath string `json:"binary_path,omitempty"`
	// Version of the service binary
	BinaryVersion string `json:"binary_version,omitempty"`
	// SHA256 checksum of the service binary for integrity verification
	BinaryChecksum string `json:"binary_checksum,omitempty"`
	// Record creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ServiceInstanceQuery when eager-loading is set.
	Edges        ServiceInstanceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ServiceInstanceEdges holds the relations/edges for other nodes in the graph.
type ServiceInstanceEdges struct {
	// The router this service instance belongs to
	Router *Router `json:"router,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RouterOrErr returns the Router value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServiceInstanceEdges) RouterOrErr() (*Router, error) {
	if e.Router != nil {
		return e.Router, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: router.Label}
	}
	return nil, &NotLoadedError{edge: "router"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ServiceInstance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case serviceinstance.FieldPorts, serviceinstance.FieldConfig:
			values[i] = new([]byte)
		case serviceinstance.FieldVlanID:
			values[i] = new(sql.NullInt64)
		case serviceinstance.FieldID, serviceinstance.FieldFeatureID, serviceinstance.FieldInstanceName, serviceinstance.FieldRouterID, serviceinstance.FieldStatus, serviceinstance.FieldBindIP, serviceinstance.FieldBinaryPath, serviceinstance.FieldBinaryVersion, serviceinstance.FieldBinaryChecksum:
			values[i] = new(sql.NullString)
		case serviceinstance.FieldCreatedAt, serviceinstance.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ServiceInstance fields.
func (_m *ServiceInstance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case serviceinstance.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case serviceinstance.FieldFeatureID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field feature_id", values[i])
			} else if value.Valid {
				_m.FeatureID = value.String
			}
		case serviceinstance.FieldInstanceName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field instance_name", values[i])
			} else if value.Valid {
				_m.InstanceName = value.String
			}
		case serviceinstance.FieldRouterID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field router_id", values[i])
			} else if value.Valid {
				_m.RouterID = value.String
			}
		case serviceinstance.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = serviceinstance.Status(value.String)
			}
		case serviceinstance.FieldVlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field vlan_id", values[i])
			} else if value.Valid {
				_m.VlanID = new(int)
				*_m.VlanID = int(value.Int64)
			}
		case serviceinstance.FieldBindIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bind_ip", values[i])
			} else if value.Valid {
				_m.BindIP = value.String
			}
		case serviceinstance.FieldPorts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field ports", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Ports); err != nil {
					return fmt.Errorf("unmarshal field ports: %w", err)
				}
			}
		case serviceinstance.FieldConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Config); err != nil {
					return fmt.Errorf("unmarshal field config: %w", err)
				}
			}
		case serviceinstance.FieldBinaryPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field binary_path", values[i])
			} else if value.Valid {
				_m.BinaryPath = value.String
			}
		case serviceinstance.FieldBinaryVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field binary_version", values[i])
			} else if value.Valid {
				_m.BinaryVersion = value.String
			}
		case serviceinstance.FieldBinaryChecksum:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field binary_checksum", values[i])
			} else if value.Valid {
				_m.BinaryChecksum = value.String
			}
		case serviceinstance.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case serviceinstance.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ServiceInstance.
// This includes values selected through modifiers, order, etc.
func (_m *ServiceInstance) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRouter queries the "router" edge of the ServiceInstance entity.
func (_m *ServiceInstance) QueryRouter() *RouterQuery {
	return NewServiceInstanceClient(_m.config).QueryRouter(_m)
}

// Update returns a builder for updating this ServiceInstance.
// Note that you need to call ServiceInstance.Unwrap() before calling this method if this ServiceInstance
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ServiceInstance) Update() *ServiceInstanceUpdateOne {
	return NewServiceInstanceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ServiceInstance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ServiceInstance) Unwrap() *ServiceInstance {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ServiceInstance is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ServiceInstance) String() string {
	var builder strings.Builder
	builder.WriteString("ServiceInstance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("feature_id=")
	builder.WriteString(_m.FeatureID)
	builder.WriteString(", ")
	builder.WriteString("instance_name=")
	builder.WriteString(_m.InstanceName)
	builder.WriteString(", ")
	builder.WriteString("router_id=")
	builder.WriteString(_m.RouterID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.VlanID; v != nil {
		builder.WriteString("vlan_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("bind_ip=")
	builder.WriteString(_m.BindIP)
	builder.WriteString(", ")
	builder.WriteString("ports=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ports))
	builder.WriteString(", ")
	builder.WriteString("config=")
	builder.WriteString(fmt.Sprintf("%v", _m.Config))
	builder.WriteString(", ")
	builder.WriteString("binary_path=")
	builder.WriteString(_m.BinaryPath)
	builder.WriteString(", ")
	builder.WriteString("binary_version=")
	builder.WriteString(_m.BinaryVersion)
	builder.WriteString(", ")
	builder.WriteString("binary_checksum=")
	builder.WriteString(_m.BinaryChecksum)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ServiceInstances is a parsable slice of ServiceInstance.
type ServiceInstances []*ServiceInstance
