import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  Button,
  Dialog,
  FieldRow,
  FieldStack,
  FormError,
  Input,
  Label,
  PasswordInput,
  Switch,
} from '@nasnet/ui';
import {
  ApiError,
  createWireguardPeer,
  type CreateWireguardPeerRequest,
  type CreateWireguardPeerResponse,
  type VPNCredentials,
} from '../../../api';
import { isPort } from '../../../utils/validators';

const ADVANCED_WG_PEER_FIELDS_ID = 'wg-peer-advanced-fields';

interface Props {
  creds: VPNCredentials | null;
  interfaceName: string;
  onCancel: () => void;
  onCreated: (created: CreateWireguardPeerResponse) => void;
}

export function AddWgPeerDialog({ creds, interfaceName, onCancel, onCreated }: Props) {
  const { t } = useTranslation('vpn');
  const [advanced, setAdvanced] = useState(false);
  const [name, setName] = useState('');
  const [endpointAddress, setEndpointAddress] = useState('');
  const [endpointPort, setEndpointPort] = useState('51820');
  const [allowedAddresses, setAllowedAddresses] = useState('');
  const [publicKey, setPublicKey] = useState('');
  const [presharedKey, setPresharedKey] = useState('');
  const [persistentKeepalive, setPersistentKeepalive] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [touched, setTouched] = useState<Record<string, boolean>>({});

  const markTouched = (key: string) =>
    setTouched((prev) => (prev[key] ? prev : { ...prev, [key]: true }));

  const errors = useMemo(
    () => ({
      endpointPort:
        !advanced || endpointAddress.trim() === '' || isPort(endpointPort)
          ? null
          : t('shared.portRange'),
      persistentKeepalive:
        !advanced ||
        persistentKeepalive.trim() === '' ||
        (Number.isInteger(Number(persistentKeepalive)) && Number(persistentKeepalive) > 0)
          ? null
          : t('shared.keepalivePositive'),
    }),
    [advanced, endpointAddress, endpointPort, persistentKeepalive, t],
  );

  const hasErrors = Object.values(errors).some(Boolean);
  const canSubmit = !!creds && !submitting && !hasErrors;

  const submit = async () => {
    setTouched({
      endpointPort: true,
      persistentKeepalive: true,
    });
    if (!canSubmit || !creds) return;
    setError(null);
    setSubmitting(true);

    const body: CreateWireguardPeerRequest = {
      interfaceName,
      savePrivateKey: true,
    };
    if (advanced) {
      if (allowedAddresses.trim()) body.allowedAddresses = allowedAddresses.trim();
      if (endpointAddress.trim()) {
        body.endpointAddress = endpointAddress.trim();
        body.endpointPort = Number(endpointPort);
      }
      if (name.trim()) body.name = name.trim();
      if (publicKey.trim()) {
        body.publicKey = publicKey.trim();
        delete body.savePrivateKey;
      }
      if (presharedKey.trim()) body.preSharedKey = presharedKey.trim();
      if (persistentKeepalive.trim()) body.persistentKeepalive = Number(persistentKeepalive);
    }

    let created: CreateWireguardPeerResponse;
    try {
      created = await createWireguardPeer(creds, body);
    } catch (err) {
      const message =
        err instanceof ApiError
          ? err.message
          : err instanceof Error
            ? err.message
            : t('wgPeerAdd.createFailed');
      setError(message);
      setSubmitting(false);
      return;
    }
    setSubmitting(false);
    onCreated(created);
  };

  return (
    <Dialog
      open
      onClose={submitting ? () => undefined : onCancel}
      title={t('wgPeerAdd.title', { name: interfaceName })}
      size="md"
      footer={
        <>
          <Button variant="ghost" onClick={onCancel} disabled={submitting}>
            {t('shared.cancel')}
          </Button>
          <Button onClick={submit} disabled={!canSubmit}>
            {submitting ? t('shared.creating') : t('wgPeerAdd.create')}
          </Button>
        </>
      }
    >
      <FieldStack>
        <p>{t('wgPeerAdd.intro')}</p>
        <FieldRow>
          <Label as="div">
            <Switch
              label={t('shared.advancedMode')}
              checked={advanced}
              onChange={(e) => setAdvanced(e.target.checked)}
              aria-expanded={advanced}
              aria-controls={ADVANCED_WG_PEER_FIELDS_ID}
            />
          </Label>
        </FieldRow>
        {advanced ? (
          <FieldStack
            id={ADVANCED_WG_PEER_FIELDS_ID}
            role="group"
            aria-label={t('wgPeerAdd.advancedGroup')}
          >
            <FieldRow>
              <Label>
                <span>{t('shared.nameOptional')}</span>
                <Input
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder={t('shared.autoGeneratedIfEmpty')}
                  aria-label={t('shared.name')}
                  autoComplete="off"
                />
              </Label>
            </FieldRow>
            <FieldRow>
              <Label>
                <span>{t('wgPeerAdd.endpointAddressOptional')}</span>
                <Input
                  value={endpointAddress}
                  onChange={(e) => setEndpointAddress(e.target.value)}
                  placeholder="203.0.113.50"
                  aria-label={t('shared.endpointAddress')}
                  dir="ltr"
                  autoComplete="off"
                />
              </Label>
              <Label>
                <span>{t('clients.form.endpointPort')}</span>
                <Input
                  value={endpointPort}
                  onChange={(e) => setEndpointPort(e.target.value)}
                  onBlur={() => markTouched('endpointPort')}
                  inputMode="numeric"
                  aria-label={t('clients.form.endpointPort')}
                  dir="ltr"
                  autoComplete="off"
                  aria-invalid={touched.endpointPort && !!errors.endpointPort}
                />
                {touched.endpointPort && errors.endpointPort ? (
                  <FormError>{errors.endpointPort}</FormError>
                ) : null}
              </Label>
            </FieldRow>
            <FieldRow>
              <Label>
                <span>{t('wgPeerAdd.allowedAddressesOptional')}</span>
                <Input
                  value={allowedAddresses}
                  onChange={(e) => setAllowedAddresses(e.target.value)}
                  placeholder={t('wgPeerAdd.peerIpIfEmpty')}
                  aria-label={t('shared.allowedAddresses')}
                  dir="ltr"
                  autoComplete="off"
                />
              </Label>
              <Label>
                <span>{t('shared.keepaliveSeconds')}</span>
                <Input
                  value={persistentKeepalive}
                  onChange={(e) => setPersistentKeepalive(e.target.value)}
                  onBlur={() => markTouched('persistentKeepalive')}
                  placeholder={t('shared.keepalivePlaceholder')}
                  inputMode="numeric"
                  aria-label={t('shared.keepalive')}
                  autoComplete="off"
                  aria-invalid={touched.persistentKeepalive && !!errors.persistentKeepalive}
                />
                {touched.persistentKeepalive && errors.persistentKeepalive ? (
                  <FormError>{errors.persistentKeepalive}</FormError>
                ) : null}
              </Label>
            </FieldRow>
            <FieldRow>
              <Label>
                <span>{t('wgPeerAdd.publicKeyPeer')}</span>
                <Input
                  value={publicKey}
                  onChange={(e) => setPublicKey(e.target.value)}
                  placeholder={t('wgPeerAdd.publicKeyPlaceholder')}
                  aria-label={t('shared.publicKey')}
                  dir="ltr"
                  autoComplete="off"
                />
              </Label>
              <Label>
                <span>{t('shared.presharedKey')}</span>
                <PasswordInput
                  value={presharedKey}
                  onChange={(e) => setPresharedKey(e.target.value)}
                  placeholder={t('shared.autoGeneratePlaceholder')}
                  aria-label={t('shared.presharedKey')}
                  dir="ltr"
                  autoComplete="new-password"
                />
              </Label>
            </FieldRow>
          </FieldStack>
        ) : null}
        {error ? <FormError role="alert">{error}</FormError> : null}
      </FieldStack>
    </Dialog>
  );
}
