/**
 * FirewallLogsPage Storybook Stories
 *
 * Interactive stories for the Firewall Logs page domain component.
 * Demonstrates the adaptive desktop (sidebar + viewer + stats panel) and
 * mobile (bottom-sheet filters + card viewer) layouts, auto-refresh controls,
 * and accessibility live-region announcements.
 *
 * @module @nasnet/features/firewall/pages
 */

import { FirewallLogsPage } from './FirewallLogsPage';

import type { Meta, StoryObj } from '@storybook/react';

/**
 * FirewallLogsPage — real-time firewall log viewer
 *
 * Main page for viewing firewall log entries generated by MikroTik's logging
 * rules. Provides:
 *
 * - **Desktop layout**: 320px filter sidebar, central log viewer, collapsible
 *   stats panel on the right.
 * - **Mobile layout**: bottom-sheet filter drawer triggered by a "Filters"
 *   button with active-filter count badge, card-based log viewer, stats card
 *   below the list.
 * - **Auto-refresh controls**: play/pause toggle + interval selector (5 s,
 *   10 s, 30 s, 60 s, manual).
 * - **Export**: CSV download of currently visible entries.
 * - **Prefix click navigation**: clicking a log prefix navigates to the
 *   matching firewall rule in the Filter/Raw/NAT/Mangle pages.
 * - **Accessibility**: ARIA live region announces new entries to screen
 *   readers without disrupting keyboard focus.
 *
 * ## Data flow
 *
 * `useFirewallLogStore` (Zustand) stores filter state, auto-refresh settings,
 * and layout state (expandedStats, filtersSheetOpen). `useFirewallLogViewer`
 * (headless hook from `@nasnet/ui/patterns`) handles polling and log
 * accumulation. `useConnectionStore` provides the active router IP.
 */
const meta: Meta<typeof FirewallLogsPage> = {
  title: 'Pages/Firewall/FirewallLogsPage',
  component: FirewallLogsPage,
  tags: ['autodocs'],
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'Real-time firewall log viewer (NAS-5.6). Adaptive layout: ' +
          'desktop shows a 3-column view (filters | log table | stats panel); ' +
          'mobile shows a bottom-sheet filter drawer and stacked card list. ' +
          'Auto-refresh interval is configurable (5 s – 60 s or manual). ' +
          'Log prefix clicks navigate to the corresponding firewall rule. ' +
          'CSV export is available at any time.',
      },
    },
    a11y: {
      config: {
        rules: [{ id: 'color-contrast', enabled: true }],
      },
    },
  },
};

export default meta;
type Story = StoryObj<typeof FirewallLogsPage>;

// ============================================================================
// Stories
// ============================================================================

/**
 * Default — Desktop layout, auto-refresh running
 *
 * The page renders with default Zustand store state: auto-refresh enabled at
 * a 10-second interval, stats panel expanded, no active filters. Actual log
 * entries depend on the MSW / Apollo mock environment.
 */
export const Default: Story = {
  parameters: {
    docs: {
      description: {
        story:
          'Default desktop render. Auto-refresh is enabled at 10 s; the stats ' +
          'panel is expanded on the right side. Filter sidebar shows all filter ' +
          'controls in an idle (no active filters) state.',
      },
    },
  },
};

/**
 * Mobile Viewport — bottom-sheet filters
 *
 * At <640px the filter sidebar is hidden; a "Filters" button in the header
 * opens a bottom sheet. The stats panel is rendered as a card below the log
 * list instead of a side panel.
 */
export const MobileViewport: Story = {
  parameters: {
    viewport: {
      defaultViewport: 'mobile1',
    },
    docs: {
      description: {
        story:
          'Mobile view (<640px). Filter sidebar is replaced by a bottom-sheet ' +
          'drawer opened by the "Filters" button. Active filter count is shown ' +
          'as a badge on the button. Stats appear as a card below the log list.',
      },
    },
  },
};

/**
 * Desktop — Stats Panel Collapsed
 *
 * The collapsible stats panel on the right is in its collapsed state,
 * showing only the expand toggle button. The log viewer gains additional
 * horizontal space.
 */
export const DesktopStatsCollapsed: Story = {
  parameters: {
    docs: {
      description: {
        story:
          'Desktop view with the stats panel collapsed. Only the expand toggle ' +
          '(chevron) is visible on the far right, giving the log table maximum ' +
          'width. Click the chevron to expand.',
      },
    },
    mockData: {
      expandedStats: false,
    },
  },
};

/**
 * Desktop — Auto-Refresh Paused
 *
 * Auto-refresh is paused (the Play button is shown instead of Pause). The
 * interval selector remains interactive so users can change the interval
 * before resuming.
 */
export const AutoRefreshPaused: Story = {
  parameters: {
    docs: {
      description: {
        story:
          'Auto-refresh paused state. The Play button replaces the Pause button ' +
          'in the controls bar. New log entries stop accumulating until the user ' +
          'resumes. Manual refresh is still possible.',
      },
    },
    mockData: {
      autoRefresh: false,
      refreshInterval: 10000,
    },
  },
};
