/**
 * FirewallLogsPage Storybook Stories
 *
 * Interactive stories for the Firewall Logs page domain component.
 * Demonstrates the adaptive desktop (sidebar + viewer + stats panel) and
 * mobile (bottom-sheet filters + card viewer) layouts, auto-refresh controls,
 * and accessibility live-region announcements.
 *
 * @module @nasnet/features/firewall/pages
 */
import { FirewallLogsPage } from './FirewallLogsPage';
import type { Meta, StoryObj } from '@storybook/react';
/**
 * FirewallLogsPage — real-time firewall log viewer
 *
 * Main page for viewing firewall log entries generated by MikroTik's logging
 * rules. Provides:
 *
 * - **Desktop layout**: 320px filter sidebar, central log viewer, collapsible
 *   stats panel on the right.
 * - **Mobile layout**: bottom-sheet filter drawer triggered by a "Filters"
 *   button with active-filter count badge, card-based log viewer, stats card
 *   below the list.
 * - **Auto-refresh controls**: play/pause toggle + interval selector (5 s,
 *   10 s, 30 s, 60 s, manual).
 * - **Export**: CSV download of currently visible entries.
 * - **Prefix click navigation**: clicking a log prefix navigates to the
 *   matching firewall rule in the Filter/Raw/NAT/Mangle pages.
 * - **Accessibility**: ARIA live region announces new entries to screen
 *   readers without disrupting keyboard focus.
 *
 * ## Data flow
 *
 * `useFirewallLogStore` (Zustand) stores filter state, auto-refresh settings,
 * and layout state (expandedStats, filtersSheetOpen). `useFirewallLogViewer`
 * (headless hook from `@nasnet/ui/patterns`) handles polling and log
 * accumulation. `useConnectionStore` provides the active router IP.
 */
declare const meta: Meta<typeof FirewallLogsPage>;
export default meta;
type Story = StoryObj<typeof FirewallLogsPage>;
/**
 * Default — Desktop layout, auto-refresh running
 *
 * The page renders with default Zustand store state: auto-refresh enabled at
 * a 10-second interval, stats panel expanded, no active filters. Actual log
 * entries depend on the MSW / Apollo mock environment.
 */
export declare const Default: Story;
/**
 * Mobile Viewport — bottom-sheet filters
 *
 * At <640px the filter sidebar is hidden; a "Filters" button in the header
 * opens a bottom sheet. The stats panel is rendered as a card below the log
 * list instead of a side panel.
 */
export declare const MobileViewport: Story;
/**
 * Desktop — Stats Panel Collapsed
 *
 * The collapsible stats panel on the right is in its collapsed state,
 * showing only the expand toggle button. The log viewer gains additional
 * horizontal space.
 */
export declare const DesktopStatsCollapsed: Story;
/**
 * Desktop — Auto-Refresh Paused
 *
 * Auto-refresh is paused (the Play button is shown instead of Pause). The
 * interval selector remains interactive so users can change the interval
 * before resuming.
 */
export declare const AutoRefreshPaused: Story;
//# sourceMappingURL=FirewallLogsPage.stories.d.ts.map