package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	graphql1 "backend/generated/graphql"
	"context"
	"fmt"
)

// ValidateServiceConfig is the resolver for the validateServiceConfig field.
func (r *mutationResolver) ValidateServiceConfig(ctx context.Context, input graphql1.ValidateServiceConfigInput) (*graphql1.ConfigValidationResult, error) {
	return nil, fmt.Errorf("not implemented")
}

// ApplyServiceConfig is the resolver for the applyServiceConfig field.
func (r *mutationResolver) ApplyServiceConfig(ctx context.Context, input graphql1.ApplyServiceConfigInput) (*graphql1.ApplyConfigPayload, error) {
	return nil, fmt.Errorf("not implemented")
}

// ServiceConfigSchema is the resolver for the serviceConfigSchema field.
func (r *queryResolver) ServiceConfigSchema(ctx context.Context, serviceType string) (*graphql1.ConfigSchema, error) {
	return nil, fmt.Errorf("not implemented")
}

// InstanceConfig is the resolver for the instanceConfig field.
func (r *queryResolver) InstanceConfig(ctx context.Context, routerID string, instanceID string) (map[string]any, error) {
	return nil, fmt.Errorf("not implemented")
}
