package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	graphql1 "backend/generated/graphql"
	"context"
	"fmt"
)

// ConfigureExternalStorage is the resolver for the configureExternalStorage field.
func (r *mutationResolver) ConfigureExternalStorage(ctx context.Context, input graphql1.ConfigureExternalStorageInput) (*graphql1.ConfigureExternalStoragePayload, error) {
	panic(fmt.Errorf("not implemented: ConfigureExternalStorage - configureExternalStorage"))
}

// ResetExternalStorage is the resolver for the resetExternalStorage field.
func (r *mutationResolver) ResetExternalStorage(ctx context.Context, input *graphql1.ResetExternalStorageInput) (*graphql1.ResetExternalStoragePayload, error) {
	panic(fmt.Errorf("not implemented: ResetExternalStorage - resetExternalStorage"))
}

// ScanStorage is the resolver for the scanStorage field.
func (r *mutationResolver) ScanStorage(ctx context.Context) (*graphql1.ScanStoragePayload, error) {
	panic(fmt.Errorf("not implemented: ScanStorage - scanStorage"))
}

// StorageInfo is the resolver for the storageInfo field.
func (r *queryResolver) StorageInfo(ctx context.Context) ([]*graphql1.StorageInfo, error) {
	panic(fmt.Errorf("not implemented: StorageInfo - storageInfo"))
}

// StorageUsage is the resolver for the storageUsage field.
func (r *queryResolver) StorageUsage(ctx context.Context, routerID *string) (*graphql1.StorageUsage, error) {
	panic(fmt.Errorf("not implemented: StorageUsage - storageUsage"))
}

// StorageConfig is the resolver for the storageConfig field.
func (r *queryResolver) StorageConfig(ctx context.Context) (*graphql1.StorageConfig, error) {
	panic(fmt.Errorf("not implemented: StorageConfig - storageConfig"))
}

// UnavailableFeatures is the resolver for the unavailableFeatures field.
func (r *queryResolver) UnavailableFeatures(ctx context.Context, routerID *string) ([]*graphql1.ServiceInstance, error) {
	panic(fmt.Errorf("not implemented: UnavailableFeatures - unavailableFeatures"))
}

// StorageMountChanged is the resolver for the storageMountChanged field.
func (r *subscriptionResolver) StorageMountChanged(ctx context.Context, path *string) (<-chan graphql1.StorageMountEvent, error) {
	panic(fmt.Errorf("not implemented: StorageMountChanged - storageMountChanged"))
}

// StorageSpaceChanged is the resolver for the storageSpaceChanged field.
func (r *subscriptionResolver) StorageSpaceChanged(ctx context.Context, path *string) (<-chan *graphql1.StorageSpaceEvent, error) {
	panic(fmt.Errorf("not implemented: StorageSpaceChanged - storageSpaceChanged"))
}
