import { Spinner } from './Spinner';
import type { Meta, StoryObj } from '@storybook/react';
declare const meta: Meta<typeof Spinner>;
export default meta;
type Story = StoryObj<typeof Spinner>;
export declare const Default: Story;
export declare const ExtraSmall: Story;
export declare const Small: Story;
export declare const Large: Story;
export declare const ExtraLarge: Story;
export declare const AllSizes: Story;
export declare const WithCustomLabel: Story;
export declare const InButtonContext: Story;
export declare const InLoadingOverlay: Story;
export declare const ColorVariants: Story;
export declare const Mobile: Story;
export declare const Tablet: Story;
export declare const Error: Story;
export declare const Empty: Story;
//# sourceMappingURL=Spinner.stories.d.ts.map