// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APIKey is the predicate function for apikey builders.
type APIKey func(*sql.Selector)

// ConfigSnapshot is the predicate function for configsnapshot builders.
type ConfigSnapshot func(*sql.Selector)

// GlobalSettings is the predicate function for globalsettings builders.
type GlobalSettings func(*sql.Selector)

// Resource is the predicate function for resource builders.
type Resource func(*sql.Selector)

// ResourceEvent is the predicate function for resourceevent builders.
type ResourceEvent func(*sql.Selector)

// Router is the predicate function for router builders.
type Router func(*sql.Selector)

// RouterCapability is the predicate function for routercapability builders.
type RouterCapability func(*sql.Selector)

// RouterSecret is the predicate function for routersecret builders.
type RouterSecret func(*sql.Selector)

// SchemaVersion is the predicate function for schemaversion builders.
type SchemaVersion func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
