import type { Meta, StoryObj } from '@storybook/react';
import { RoutingChainViz } from './RoutingChainViz';
declare const meta: Meta<typeof RoutingChainViz>;
export default meta;
type Story = StoryObj<typeof RoutingChainViz>;
export declare const Default: Story;
export declare const SingleHop: Story;
export declare const MultiHop: Story;
export declare const UnhealthyHop: Story;
export declare const HighLatency: Story;
export declare const KillSwitchActive: Story;
export declare const KillSwitchModes: Story;
export declare const Loading: Story;
export declare const Error: Story;
export declare const Compact: Story;
export declare const Inactive: Story;
export declare const WithoutLatency: Story;
export declare const WithoutKillSwitch: Story;
export declare const CustomDeviceLabel: Story;
export declare const Interactive: Story;
//# sourceMappingURL=RoutingChainViz.stories.d.ts.map