package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"backend/graph/model"
	"backend/internal/errors"
	"context"
)

// UpdateRouterCredentials is the resolver for the updateRouterCredentials field.
func (r *mutationResolver) UpdateRouterCredentials(ctx context.Context, routerID string, input model.CredentialsInput) (*model.CredentialUpdatePayload, error) {
	panic(errors.NewInternalError("not implemented: UpdateRouterCredentials - updateRouterCredentials", nil))
}

// TestAllCredentials is the resolver for the testAllCredentials field.
func (r *mutationResolver) TestAllCredentials(ctx context.Context) (*model.TestAllCredentialsPayload, error) {
	panic(errors.NewInternalError("not implemented: TestAllCredentials - testAllCredentials", nil))
}

// ExportRouterConfig is the resolver for the exportRouterConfig field.
func (r *mutationResolver) ExportRouterConfig(ctx context.Context, input model.ExportConfigInput) (*model.ExportConfigPayload, error) {
	panic(errors.NewInternalError("not implemented: ExportRouterConfig - exportRouterConfig", nil))
}

// RouterCredentials is the resolver for the routerCredentials field.
func (r *queryResolver) RouterCredentials(ctx context.Context, routerID string) (*model.RouterCredentials, error) {
	panic(errors.NewInternalError("not implemented: RouterCredentials - routerCredentials", nil))
}
