package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"backend/graph/model"
	"context"
	"fmt"
)

// StartTroubleshoot is the resolver for the startTroubleshoot field.
func (r *mutationResolver) StartTroubleshoot(ctx context.Context, routerID string) (*model.StartTroubleshootPayload, error) {
	panic(fmt.Errorf("not implemented: StartTroubleshoot - startTroubleshoot"))
}

// RunTroubleshootStep is the resolver for the runTroubleshootStep field.
func (r *mutationResolver) RunTroubleshootStep(ctx context.Context, sessionID string, stepType model.TroubleshootStepType) (*model.RunTroubleshootStepPayload, error) {
	panic(fmt.Errorf("not implemented: RunTroubleshootStep - runTroubleshootStep"))
}

// ApplyTroubleshootFix is the resolver for the applyTroubleshootFix field.
func (r *mutationResolver) ApplyTroubleshootFix(ctx context.Context, sessionID string, issueCode string) (*model.ApplyFixPayload, error) {
	panic(fmt.Errorf("not implemented: ApplyTroubleshootFix - applyTroubleshootFix"))
}

// VerifyTroubleshootFix is the resolver for the verifyTroubleshootFix field.
func (r *mutationResolver) VerifyTroubleshootFix(ctx context.Context, sessionID string, stepType model.TroubleshootStepType) (*model.RunTroubleshootStepPayload, error) {
	panic(fmt.Errorf("not implemented: VerifyTroubleshootFix - verifyTroubleshootFix"))
}

// CancelTroubleshoot is the resolver for the cancelTroubleshoot field.
func (r *mutationResolver) CancelTroubleshoot(ctx context.Context, sessionID string) (*model.TroubleshootSession, error) {
	panic(fmt.Errorf("not implemented: CancelTroubleshoot - cancelTroubleshoot"))
}

// TroubleshootSession is the resolver for the troubleshootSession field.
func (r *queryResolver) TroubleshootSession(ctx context.Context, id string) (*model.TroubleshootSession, error) {
	panic(fmt.Errorf("not implemented: TroubleshootSession - troubleshootSession"))
}

// DetectWanInterface is the resolver for the detectWanInterface field.
func (r *queryResolver) DetectWanInterface(ctx context.Context, routerID string) (string, error) {
	panic(fmt.Errorf("not implemented: DetectWanInterface - detectWanInterface"))
}

// DetectGateway is the resolver for the detectGateway field.
func (r *queryResolver) DetectGateway(ctx context.Context, routerID string) (*string, error) {
	panic(fmt.Errorf("not implemented: DetectGateway - detectGateway"))
}

// DetectIsp is the resolver for the detectISP field.
func (r *queryResolver) DetectIsp(ctx context.Context, routerID string) (*model.ISPInfo, error) {
	panic(fmt.Errorf("not implemented: DetectIsp - detectISP"))
}

// TroubleshootProgress is the resolver for the troubleshootProgress field.
func (r *subscriptionResolver) TroubleshootProgress(ctx context.Context, sessionID string) (<-chan *model.TroubleshootSession, error) {
	panic(fmt.Errorf("not implemented: TroubleshootProgress - troubleshootProgress"))
}
