package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"backend/graph/model"
	"context"
	"fmt"
)

// RunDiagnostics is the resolver for the runDiagnostics field.
func (r *mutationResolver) RunDiagnostics(ctx context.Context, routerID string) (*model.DiagnosticReport, error) {
	panic(fmt.Errorf("not implemented: RunDiagnostics - runDiagnostics"))
}

// ResetCircuitBreaker is the resolver for the resetCircuitBreaker field.
func (r *mutationResolver) ResetCircuitBreaker(ctx context.Context, routerID string) (*model.CircuitBreakerStatus, error) {
	panic(fmt.Errorf("not implemented: ResetCircuitBreaker - resetCircuitBreaker"))
}

// StartTroubleshoot is the resolver for the startTroubleshoot field.
func (r *mutationResolver) StartTroubleshoot(ctx context.Context, routerID string) (*model.StartTroubleshootPayload, error) {
	panic(fmt.Errorf("not implemented: StartTroubleshoot - startTroubleshoot"))
}

// RunTroubleshootStep is the resolver for the runTroubleshootStep field.
func (r *mutationResolver) RunTroubleshootStep(ctx context.Context, sessionID string, stepType model.TroubleshootStepType) (*model.RunTroubleshootStepPayload, error) {
	panic(fmt.Errorf("not implemented: RunTroubleshootStep - runTroubleshootStep"))
}

// ApplyTroubleshootFix is the resolver for the applyTroubleshootFix field.
func (r *mutationResolver) ApplyTroubleshootFix(ctx context.Context, sessionID string, issueCode string) (*model.ApplyFixPayload, error) {
	panic(fmt.Errorf("not implemented: ApplyTroubleshootFix - applyTroubleshootFix"))
}

// VerifyTroubleshootFix is the resolver for the verifyTroubleshootFix field.
func (r *mutationResolver) VerifyTroubleshootFix(ctx context.Context, sessionID string, stepType model.TroubleshootStepType) (*model.RunTroubleshootStepPayload, error) {
	panic(fmt.Errorf("not implemented: VerifyTroubleshootFix - verifyTroubleshootFix"))
}

// CancelTroubleshoot is the resolver for the cancelTroubleshoot field.
func (r *mutationResolver) CancelTroubleshoot(ctx context.Context, sessionID string) (*model.TroubleshootSession, error) {
	panic(fmt.Errorf("not implemented: CancelTroubleshoot - cancelTroubleshoot"))
}

// RunTraceroute is the resolver for the runTraceroute field.
func (r *mutationResolver) RunTraceroute(ctx context.Context, deviceID string, input model.TracerouteInput) (*model.TracerouteJob, error) {
	panic(fmt.Errorf("not implemented: RunTraceroute - runTraceroute"))
}

// CancelTraceroute is the resolver for the cancelTraceroute field.
func (r *mutationResolver) CancelTraceroute(ctx context.Context, jobID string) (bool, error) {
	panic(fmt.Errorf("not implemented: CancelTraceroute - cancelTraceroute"))
}

// RunDNSLookup is the resolver for the runDnsLookup field.
func (r *mutationResolver) RunDNSLookup(ctx context.Context, input model.DNSLookupInput) (*model.DNSLookupResult, error) {
	panic(fmt.Errorf("not implemented: RunDNSLookup - runDnsLookup"))
}

// FlushDNSCache is the resolver for the flushDnsCache field.
func (r *mutationResolver) FlushDNSCache(ctx context.Context, deviceID string) (*model.FlushDNSCacheResult, error) {
	panic(fmt.Errorf("not implemented: FlushDNSCache - flushDnsCache"))
}

// ConnectionAttempts is the resolver for the connectionAttempts field.
func (r *queryResolver) ConnectionAttempts(ctx context.Context, routerID string, limit *int) ([]*model.ConnectionAttempt, error) {
	panic(fmt.Errorf("not implemented: ConnectionAttempts - connectionAttempts"))
}

// CircuitBreakerStatus is the resolver for the circuitBreakerStatus field.
func (r *queryResolver) CircuitBreakerStatus(ctx context.Context, routerID string) (*model.CircuitBreakerStatus, error) {
	panic(fmt.Errorf("not implemented: CircuitBreakerStatus - circuitBreakerStatus"))
}

// TroubleshootSession is the resolver for the troubleshootSession field.
func (r *queryResolver) TroubleshootSession(ctx context.Context, id string) (*model.TroubleshootSession, error) {
	panic(fmt.Errorf("not implemented: TroubleshootSession - troubleshootSession"))
}

// DetectWanInterface is the resolver for the detectWanInterface field.
func (r *queryResolver) DetectWanInterface(ctx context.Context, routerID string) (string, error) {
	panic(fmt.Errorf("not implemented: DetectWanInterface - detectWanInterface"))
}

// DetectGateway is the resolver for the detectGateway field.
func (r *queryResolver) DetectGateway(ctx context.Context, routerID string) (*string, error) {
	panic(fmt.Errorf("not implemented: DetectGateway - detectGateway"))
}

// DetectIsp is the resolver for the detectISP field.
func (r *queryResolver) DetectIsp(ctx context.Context, routerID string) (*model.ISPInfo, error) {
	panic(fmt.Errorf("not implemented: DetectIsp - detectISP"))
}

// DNSServers is the resolver for the dnsServers field.
func (r *queryResolver) DNSServers(ctx context.Context, deviceID string) (*model.DNSServers, error) {
	panic(fmt.Errorf("not implemented: DNSServers - dnsServers"))
}

// DNSCacheStats is the resolver for the dnsCacheStats field.
func (r *queryResolver) DNSCacheStats(ctx context.Context, deviceID string) (*model.DNSCacheStats, error) {
	panic(fmt.Errorf("not implemented: DNSCacheStats - dnsCacheStats"))
}

// DNSBenchmark is the resolver for the dnsBenchmark field.
func (r *queryResolver) DNSBenchmark(ctx context.Context, deviceID string) (*model.DNSBenchmarkResult, error) {
	panic(fmt.Errorf("not implemented: DNSBenchmark - dnsBenchmark"))
}

// RouteLookup is the resolver for the routeLookup field.
func (r *queryResolver) RouteLookup(ctx context.Context, routerID string, destination model.IPv4, source *model.IPv4) (*model.RouteLookupResult, error) {
	panic(fmt.Errorf("not implemented: RouteLookup - routeLookup"))
}

// CircuitBreakerStateChanged is the resolver for the circuitBreakerStateChanged field.
func (r *subscriptionResolver) CircuitBreakerStateChanged(ctx context.Context, routerID *string) (<-chan *model.CircuitBreakerStatus, error) {
	panic(fmt.Errorf("not implemented: CircuitBreakerStateChanged - circuitBreakerStateChanged"))
}

// TroubleshootProgress is the resolver for the troubleshootProgress field.
func (r *subscriptionResolver) TroubleshootProgress(ctx context.Context, sessionID string) (<-chan *model.TroubleshootSession, error) {
	panic(fmt.Errorf("not implemented: TroubleshootProgress - troubleshootProgress"))
}

// TracerouteProgress is the resolver for the tracerouteProgress field.
func (r *subscriptionResolver) TracerouteProgress(ctx context.Context, jobID string) (<-chan *model.TracerouteProgressEvent, error) {
	panic(fmt.Errorf("not implemented: TracerouteProgress - tracerouteProgress"))
}
