package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"backend/graph/model"
	"backend/internal/errors"
	"context"
)

// RunTraceroute is the resolver for the runTraceroute field.
func (r *mutationResolver) RunTraceroute(ctx context.Context, deviceID string, input model.TracerouteInput) (*model.TracerouteJob, error) {
	// Validate required inputs
	if deviceID == "" {
		panic(errors.NewValidationError("input", nil, "deviceID cannot be empty"))
	}
	if input.Target == "" {
		panic(errors.NewValidationError("input", nil, "target address cannot be empty"))
	}
	// Context used for request timeout and potential cancellation
	_ = ctx
	panic(errors.NewValidationError("input", nil, "not implemented: RunTraceroute - runTraceroute"))
}

// CancelTraceroute is the resolver for the cancelTraceroute field.
func (r *mutationResolver) CancelTraceroute(ctx context.Context, jobID string) (bool, error) {
	if jobID == "" {
		panic(errors.NewValidationError("input", nil, "jobID cannot be empty"))
	}
	// Context used for request timeout handling
	_ = ctx
	panic(errors.NewValidationError("input", nil, "not implemented: CancelTraceroute - cancelTraceroute"))
}

// TracerouteProgress is the resolver for the tracerouteProgress field.
func (r *subscriptionResolver) TracerouteProgress(ctx context.Context, jobID string) (<-chan *model.TracerouteProgressEvent, error) {
	if jobID == "" {
		panic(errors.NewValidationError("input", nil, "jobID cannot be empty"))
	}
	// Context used for subscription timeout and cancellation
	_ = ctx
	panic(errors.NewValidationError("input", nil, "not implemented: TracerouteProgress - tracerouteProgress"))
}
