package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"backend/graph/model"
	"backend/internal/apperrors"
	"context"
)

// AddressLists is the resolver for the addressLists field.
func (r *queryResolver) AddressLists(ctx context.Context, routerID string) ([]*model.AddressList, error) {
	// Validation: routerID is required
	if routerID == "" {
		return nil, apperrors.NewValidationError("input", nil, "routerID is required")
	}

	// TODO: Implement AddressLists - query address lists from router
	panic(apperrors.NewProtocolError(apperrors.CodeCommandFailed, "not implemented: AddressLists - addressLists", "graphql"))
}

// AddressListEntries is the resolver for the addressListEntries field.
func (r *queryResolver) AddressListEntries(ctx context.Context, routerID string, listName string, first *int, after *string) (*model.AddressListEntryConnection, error) {
	// Validation: required fields
	if routerID == "" {
		return nil, apperrors.NewValidationError("input", nil, "routerID is required")
	}
	if listName == "" {
		return nil, apperrors.NewValidationError("input", nil, "listName is required")
	}

	// Validation: pagination
	if first != nil && *first < 0 {
		return nil, apperrors.NewValidationError("input", nil, "first must be non-negative")
	}

	// TODO: Implement AddressListEntries - query entries with pagination
	panic(apperrors.NewProtocolError(apperrors.CodeCommandFailed, "not implemented: AddressListEntries - addressListEntries", "graphql"))
}

// RulesReferencingAddressList is the resolver for the rulesReferencingAddressList field.
func (r *queryResolver) RulesReferencingAddressList(ctx context.Context, routerID string, listName string) ([]*model.FirewallRule, error) {
	// Validation: required fields
	if routerID == "" {
		return nil, apperrors.NewValidationError("input", nil, "routerID is required")
	}
	if listName == "" {
		return nil, apperrors.NewValidationError("input", nil, "listName is required")
	}

	// TODO: Implement RulesReferencingAddressList - find rules that reference this list
	panic(apperrors.NewProtocolError(
		apperrors.CodeCommandFailed,
		"not implemented: RulesReferencingAddressList - rulesReferencingAddressList",
		"graphql",
	))
}
