package resolver

// This file contains subscription resolvers for routing schedules.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"backend/graph/model"
	"context"

	"backend/internal/errors"
	"backend/internal/events"
)

// ScheduleChanged subscribes to schedule change events.
func (r *subscriptionResolver) ScheduleChanged(ctx context.Context, routerID string) (<-chan *model.ScheduleEvent, error) {
	r.log.Infow("ScheduleChanged subscription started",
		"routerID", routerID)

	// Create channel for events
	eventChan := make(chan *model.ScheduleEvent, 10)

	// Subscribe to schedule events via event bus
	if r.EventBus == nil {
		close(eventChan)
		return eventChan, errors.NewInternalError("event bus not available", nil)
	}

	// Track the unsubscribe handler for cleanup
	var unsubscribe func() error

	// Subscribe to schedule events via event bus handler
	handler := func(ctx context.Context, event events.Event) error {
		scheduleEvent := &model.ScheduleEvent{
			ID:        event.GetID().String(),
			EventType: event.GetType(),
			Timestamp: event.GetTimestamp(),
		}

		select {
		case eventChan <- scheduleEvent:
		case <-ctx.Done():
		}
		return nil
	}

	err := r.EventBus.Subscribe("schedule.*", handler)
	if err != nil {
		close(eventChan)
		return eventChan, errors.NewInternalError("failed to subscribe to schedule events", err)
	}

	// Get unsubscribe function if available
	if ub, ok := r.EventBus.(interface{ Unsubscribe(topic string) error }); ok {
		unsubscribe = func() error {
			return ub.Unsubscribe("schedule.*")
		}
	}

	// Close channel when context is done
	go func() {
		defer func() {
			if r := recover(); r != nil {
				// Log panic but don't crash service
				_ = r
			}
			close(eventChan)
		}()
		<-ctx.Done()
		r.log.Infow("ScheduleChanged subscription ended",
			"routerID", routerID)

		// Unsubscribe from event bus if available
		if unsubscribe != nil {
			if err := unsubscribe(); err != nil {
				r.log.Errorw("failed to unsubscribe from schedule events",
					"error", err,
					"routerID", routerID)
			}
		}
	}()

	return eventChan, nil
}
