package resolver

// This file contains subscription resolvers for routing schedules.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"backend/graph/model"
	"context"
	"fmt"

	"backend/internal/events"
)

// ScheduleChanged subscribes to schedule change events.
func (r *subscriptionResolver) ScheduleChanged(ctx context.Context, routerID string) (<-chan *model.ScheduleEvent, error) {
	r.log.Infow("ScheduleChanged subscription started",
		"routerID", routerID)

	// Create channel for events
	eventChan := make(chan *model.ScheduleEvent, 10)

	// Subscribe to schedule events via event bus
	if r.EventBus == nil {
		close(eventChan)
		return eventChan, fmt.Errorf("event bus not available")
	}

	// Subscribe to schedule events via event bus handler
	err := r.EventBus.Subscribe("schedule.*", func(ctx context.Context, event events.Event) error {
		scheduleEvent := &model.ScheduleEvent{
			ID:        event.GetID().String(),
			EventType: event.GetType(),
			Timestamp: event.GetTimestamp(),
		}

		select {
		case eventChan <- scheduleEvent:
		case <-ctx.Done():
		}
		return nil
	})
	if err != nil {
		close(eventChan)
		return eventChan, fmt.Errorf("failed to subscribe to schedule events: %w", err)
	}

	// Close channel when context is done
	go func() {
		<-ctx.Done()
		r.log.Infow("ScheduleChanged subscription ended",
			"routerID", routerID)
		close(eventChan)
	}()

	return eventChan, nil
}
