package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	graphql1 "backend/graph/model"
	"context"
	"fmt"
)

// ExportServiceConfig is the resolver for the exportServiceConfig field.
func (r *mutationResolver) ExportServiceConfig(ctx context.Context, input graphql1.ExportServiceConfigInput) (*graphql1.ExportServiceConfigPayload, error) {
	panic(fmt.Errorf("not implemented: ExportServiceConfig - exportServiceConfig"))
}

// ImportServiceConfig is the resolver for the importServiceConfig field.
func (r *mutationResolver) ImportServiceConfig(ctx context.Context, input graphql1.ImportServiceConfigInput) (*graphql1.ImportServiceConfigPayload, error) {
	panic(fmt.Errorf("not implemented: ImportServiceConfig - importServiceConfig"))
}

// ApplyServiceImport is the resolver for the applyServiceImport field.
func (r *mutationResolver) ApplyServiceImport(ctx context.Context, input graphql1.ApplyServiceImportInput) (*graphql1.ApplyServiceImportPayload, error) {
	panic(fmt.Errorf("not implemented: ApplyServiceImport - applyServiceImport"))
}

// GenerateConfigQR is the resolver for the generateConfigQR field.
func (r *mutationResolver) GenerateConfigQR(ctx context.Context, input graphql1.GenerateConfigQRInput) (*graphql1.GenerateConfigQRPayload, error) {
	panic(fmt.Errorf("not implemented: GenerateConfigQR - generateConfigQR"))
}

// ServiceConfigShared is the resolver for the serviceConfigShared field.
func (r *subscriptionResolver) ServiceConfigShared(ctx context.Context, routerID string) (<-chan *graphql1.ServiceConfigSharedEvent, error) {
	panic(fmt.Errorf("not implemented: ServiceConfigShared - serviceConfigShared"))
}
