package resolver

// This file contains mutations for updating and managing service instances.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"backend/generated/ent/serviceinstance"
	"backend/graph/model"
	"backend/internal/errors"
	"context"
)

// UpdateInstance triggers update for a specific service instance.
func (r *mutationResolver) UpdateInstance(ctx context.Context, routerID string, instanceID string) (*model.UpdateResult, error) {
	// Authorization check
	if _, ok := ctx.Value(contextKeyUserID).(string); !ok {
		return nil, errors.NewValidationError("userID", "", "authentication required")
	}

	// Input validation
	if routerID == "" {
		return nil, errors.NewValidationError("routerID", "", "required")
	}
	if instanceID == "" {
		return nil, errors.NewValidationError("instanceID", "", "required")
	}

	// Service availability check
	if r.UpdateService == nil {
		return nil, errors.NewProtocolError(errors.CodeCommandFailed, "update service not initialized", "graphql")
	}

	instance, err := r.db.ServiceInstance.Get(ctx, instanceID)
	if err != nil {
		return nil, errors.Wrap(err, errors.CodeProtocolError, errors.CategoryProtocol, "failed to query service instance")
	}

	updateInfo, available, err := r.UpdateService.CheckForUpdate(
		ctx,
		instance.FeatureID,
		instance.BinaryVersion,
	)
	if err != nil {
		return nil, errors.Wrap(err, errors.CodeProtocolError, errors.CategoryProtocol, "failed to check for update")
	}

	if !available {
		msg := "No update available"
		return &model.UpdateResult{
			Success:      false,
			InstanceID:   instanceID,
			ErrorMessage: &msg,
		}, nil
	}

	r.log.Infow("update triggered",
		"instance_id", instanceID,
		"from_version", instance.BinaryVersion,
		"to_version", updateInfo.AvailableVersion)

	return &model.UpdateResult{
		Success:    true,
		InstanceID: instanceID,
		Version:    &updateInfo.AvailableVersion,
	}, nil
}

// UpdateAllInstances triggers updates for all instances with available updates.
func (r *mutationResolver) UpdateAllInstances(ctx context.Context, routerID string, minSeverity *model.UpdateSeverity) (int, error) {
	// Authorization check
	if _, ok := ctx.Value(contextKeyUserID).(string); !ok {
		return 0, errors.NewValidationError("userID", "", "authentication required")
	}

	// Input validation
	if routerID == "" {
		return 0, errors.NewValidationError("routerID", "", "required")
	}

	// Service availability check
	if r.UpdateService == nil {
		return 0, errors.NewProtocolError(errors.CodeCommandFailed, "update service not initialized", "graphql")
	}

	instances, err := r.db.ServiceInstance.Query().
		Where(serviceinstance.RouterIDEQ(routerID)).
		All(ctx)
	if err != nil {
		return 0, errors.Wrap(err, errors.CodeProtocolError, errors.CategoryProtocol, "failed to query service instances")
	}

	updatesQueued := 0
	for _, instance := range instances {
		updateInfo, available, err := r.UpdateService.CheckForUpdate(
			ctx,
			instance.FeatureID,
			instance.BinaryVersion,
		)
		if err != nil {
			r.log.Errorw("failed to check for update",
				"instance_id", instance.ID,
				"error", err)
			continue
		}

		if !available {
			continue
		}

		// Check if update meets minimum severity threshold (if specified)
		if minSeverity != nil {
			if !severityMeetsThreshold(model.UpdateSeverity(updateInfo.Severity), *minSeverity) {
				r.log.Infow("update skipped due to severity threshold",
					"instance_id", instance.ID,
					"update_severity", updateInfo.Severity,
					"min_severity", *minSeverity)
				continue
			}
		}

		r.log.Infow("update queued",
			"instance_id", instance.ID,
			"from_version", instance.BinaryVersion,
			"to_version", updateInfo.AvailableVersion)
		updatesQueued++
	}

	return updatesQueued, nil
}
