package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"backend/generated/ent"
	"backend/generated/ent/serviceinstance"
	"backend/graph/model"
	"context"
	"fmt"
	"time"
)

// InstanceIsolation is the resolver for the instanceIsolation query field.
// Returns complete isolation status including violations and resource limits.
func (r *queryResolver) InstanceIsolation(ctx context.Context, routerID string, instanceID string) (*model.IsolationStatus, error) {
	r.log.Infow("InstanceIsolation query called",
		"routerID", routerID,
		"instanceID", instanceID)

	// Load the service instance from database
	instance, err := r.db.ServiceInstance.Query().
		Where(serviceinstance.IDEQ(instanceID)).
		Where(serviceinstance.RouterIDEQ(routerID)).
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("service instance not found: %s", instanceID)
		}
		r.log.Errorw("failed to query service instance",
			"error", err,
			"instanceID", instanceID)
		return nil, fmt.Errorf("failed to query service instance: %w", err)
	}

	// Initialize isolation status with empty violations
	isolationStatus := &model.IsolationStatus{
		Violations:   []*model.IsolationViolation{},
		LastVerified: nil,
	}

	// Check if IsolationVerifier is available
	isolationVerifier := r.InstanceManager.IsolationVerifier()
	if r.InstanceManager == nil || isolationVerifier == nil {
		r.log.Infow("IsolationVerifier not available, returning empty status",
			"instanceID", instanceID)

		// Return empty status with nil resource limits (verifier unavailable)
		return isolationStatus, nil
	}

	// Run isolation verification
	report, err := isolationVerifier.VerifyPreStart(ctx, instance)
	if err != nil {
		r.log.Errorw("failed to run isolation verification",
			"error", err,
			"instanceID", instanceID)
		return nil, fmt.Errorf("failed to run isolation verification: %w", err)
	}

	// Convert violations to GraphQL model
	now := time.Now()
	for _, violation := range report.Violations {
		isolationStatus.Violations = append(isolationStatus.Violations, &model.IsolationViolation{
			Layer:     violation.Layer,
			Severity:  convertIsolationSeverity(violation.Severity),
			Message:   violation.Description,
			Timestamp: now,
		})
	}

	isolationStatus.LastVerified = &now

	// Get resource limits if ResourceLimiter is available
	resourceLimiter := r.InstanceManager.ResourceLimiter()
	if resourceLimiter != nil {
		// Check if instance is running (has PID)
		// For MVP, we assume memory limit is stored somewhere or use default
		// In production, this would query actual cgroup limits
		resourceLimits := &model.ResourceLimits{
			MemoryMb:   50, // Default 50MB (would come from cgroup or database)
			CPUPercent: nil,
			Applied:    resourceLimiter.IsCgroupsEnabled(),
		}
		isolationStatus.ResourceLimits = resourceLimits
	}

	r.log.Infow("isolation status retrieved",
		"instanceID", instanceID,
		"violationCount", len(isolationStatus.Violations),
		"passed", len(isolationStatus.Violations) == 0)

	return isolationStatus, nil
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) InstanceIsolation(ctx context.Context, routerID string, instanceID string) (*model.IsolationStatus, error) {
	r.log.Infow("InstanceIsolation query called",
		"routerID", routerID,
		"instanceID", instanceID)

	// Load the service instance from database
	instance, err := r.db.ServiceInstance.Query().
		Where(serviceinstance.IDEQ(instanceID)).
		Where(serviceinstance.RouterIDEQ(routerID)).
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("service instance not found: %s", instanceID)
		}
		r.log.Errorw("failed to query service instance",
			"error", err,
			"instanceID", instanceID)
		return nil, fmt.Errorf("failed to query service instance: %w", err)
	}

	// Initialize isolation status with empty violations
	isolationStatus := &model.IsolationStatus{
		Violations:   []*model.IsolationViolation{},
		LastVerified: nil,
	}

	// Check if IsolationVerifier is available
	isolationVerifier := r.InstanceManager.IsolationVerifier()
	if r.InstanceManager == nil || isolationVerifier == nil {
		r.log.Infow("IsolationVerifier not available, returning empty status",
			"instanceID", instanceID)

		// Return empty status with nil resource limits (verifier unavailable)
		return isolationStatus, nil
	}

	// Run isolation verification
	report, err := isolationVerifier.VerifyPreStart(ctx, instance)
	if err != nil {
		r.log.Errorw("failed to run isolation verification",
			"error", err,
			"instanceID", instanceID)
		return nil, fmt.Errorf("failed to run isolation verification: %w", err)
	}

	// Convert violations to GraphQL model
	now := time.Now()
	for _, violation := range report.Violations {
		isolationStatus.Violations = append(isolationStatus.Violations, &model.IsolationViolation{
			Layer:     violation.Layer,
			Severity:  convertIsolationSeverity(violation.Severity),
			Message:   violation.Description,
			Timestamp: now,
		})
	}

	isolationStatus.LastVerified = &now

	// Get resource limits if ResourceLimiter is available
	resourceLimiter := r.InstanceManager.ResourceLimiter()
	if resourceLimiter != nil {
		// Check if instance is running (has PID)
		// For MVP, we assume memory limit is stored somewhere or use default
		// In production, this would query actual cgroup limits
		resourceLimits := &model.ResourceLimits{
			MemoryMb:   50, // Default 50MB (would come from cgroup or database)
			CPUPercent: nil,
			Applied:    resourceLimiter.IsCgroupsEnabled(),
		}
		isolationStatus.ResourceLimits = resourceLimits
	}

	r.log.Infow("isolation status retrieved",
		"instanceID", instanceID,
		"violationCount", len(isolationStatus.Violations),
		"passed", len(isolationStatus.Violations) == 0)

	return isolationStatus, nil
}
*/
