package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"backend/generated/ent/serviceinstance"
	"backend/internal/apperrors"
	"context"
)

// CheckForUpdates manually triggers update check for router's service instances.
func (r *mutationResolver) CheckForUpdates(ctx context.Context, routerID string) (int, error) {
	// Authorization check
	if _, ok := ctx.Value(contextKeyUserID).(string); !ok {
		return 0, apperrors.NewValidationError("userID", "", "authentication required")
	}

	// Input validation
	if routerID == "" {
		return 0, apperrors.NewValidationError("routerID", "", "required")
	}

	// Service availability check
	if r.UpdateService == nil {
		return 0, apperrors.NewProtocolError(apperrors.CodeCommandFailed, "update service not initialized", "graphql")
	}

	instances, err := r.db.ServiceInstance.Query().
		Where(serviceinstance.RouterIDEQ(routerID)).
		All(ctx)
	if err != nil {
		return 0, apperrors.Wrap(err, apperrors.CodeProtocolError, apperrors.CategoryProtocol, "failed to query service instances")
	}

	updatesFound := 0
	for _, instance := range instances {
		_, available, err := r.UpdateService.CheckForUpdate(
			ctx,
			instance.FeatureID,
			instance.BinaryVersion,
		)
		if err != nil {
			r.log.Errorw("failed to check for update",
				"instance_id", instance.ID,
				"error", err)
			continue
		}
		if available {
			updatesFound++
		}
	}

	return updatesFound, nil
}
