// Code generated by ent, DO NOT EDIT.

package routercapability

import (
	"backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldContainsFold(FieldID, id))
}

// Architecture applies equality check predicate on the "architecture" field. It's identical to ArchitectureEQ.
func Architecture(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldArchitecture, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldModel, v))
}

// BoardName applies equality check predicate on the "board_name" field. It's identical to BoardNameEQ.
func BoardName(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldBoardName, v))
}

// TotalMemory applies equality check predicate on the "total_memory" field. It's identical to TotalMemoryEQ.
func TotalMemory(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldTotalMemory, v))
}

// AvailableStorage applies equality check predicate on the "available_storage" field. It's identical to AvailableStorageEQ.
func AvailableStorage(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldAvailableStorage, v))
}

// CPUCount applies equality check predicate on the "cpu_count" field. It's identical to CPUCountEQ.
func CPUCount(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldCPUCount, v))
}

// HasWirelessChip applies equality check predicate on the "has_wireless_chip" field. It's identical to HasWirelessChipEQ.
func HasWirelessChip(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldHasWirelessChip, v))
}

// HasLteModule applies equality check predicate on the "has_lte_module" field. It's identical to HasLteModuleEQ.
func HasLteModule(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldHasLteModule, v))
}

// VersionRaw applies equality check predicate on the "version_raw" field. It's identical to VersionRawEQ.
func VersionRaw(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldVersionRaw, v))
}

// VersionMajor applies equality check predicate on the "version_major" field. It's identical to VersionMajorEQ.
func VersionMajor(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldVersionMajor, v))
}

// VersionMinor applies equality check predicate on the "version_minor" field. It's identical to VersionMinorEQ.
func VersionMinor(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldVersionMinor, v))
}

// VersionPatch applies equality check predicate on the "version_patch" field. It's identical to VersionPatchEQ.
func VersionPatch(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldVersionPatch, v))
}

// LicenseLevel applies equality check predicate on the "license_level" field. It's identical to LicenseLevelEQ.
func LicenseLevel(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldLicenseLevel, v))
}

// UpdateChannel applies equality check predicate on the "update_channel" field. It's identical to UpdateChannelEQ.
func UpdateChannel(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldUpdateChannel, v))
}

// ContainerPackageInstalled applies equality check predicate on the "container_package_installed" field. It's identical to ContainerPackageInstalledEQ.
func ContainerPackageInstalled(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldContainerPackageInstalled, v))
}

// ContainerEnabled applies equality check predicate on the "container_enabled" field. It's identical to ContainerEnabledEQ.
func ContainerEnabled(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldContainerEnabled, v))
}

// ContainerRegistryConfigured applies equality check predicate on the "container_registry_configured" field. It's identical to ContainerRegistryConfiguredEQ.
func ContainerRegistryConfigured(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldContainerRegistryConfigured, v))
}

// ContainerStorageAvailable applies equality check predicate on the "container_storage_available" field. It's identical to ContainerStorageAvailableEQ.
func ContainerStorageAvailable(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldContainerStorageAvailable, v))
}

// SupportsNetworkNamespace applies equality check predicate on the "supports_network_namespace" field. It's identical to SupportsNetworkNamespaceEQ.
func SupportsNetworkNamespace(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldSupportsNetworkNamespace, v))
}

// MaxContainers applies equality check predicate on the "max_containers" field. It's identical to MaxContainersEQ.
func MaxContainers(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldMaxContainers, v))
}

// DetectedAt applies equality check predicate on the "detected_at" field. It's identical to DetectedAtEQ.
func DetectedAt(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldDetectedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldExpiresAt, v))
}

// IsRefreshing applies equality check predicate on the "is_refreshing" field. It's identical to IsRefreshingEQ.
func IsRefreshing(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldIsRefreshing, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldUpdatedAt, v))
}

// ArchitectureEQ applies the EQ predicate on the "architecture" field.
func ArchitectureEQ(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldArchitecture, v))
}

// ArchitectureNEQ applies the NEQ predicate on the "architecture" field.
func ArchitectureNEQ(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldArchitecture, v))
}

// ArchitectureIn applies the In predicate on the "architecture" field.
func ArchitectureIn(vs ...string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldArchitecture, vs...))
}

// ArchitectureNotIn applies the NotIn predicate on the "architecture" field.
func ArchitectureNotIn(vs ...string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldArchitecture, vs...))
}

// ArchitectureGT applies the GT predicate on the "architecture" field.
func ArchitectureGT(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldArchitecture, v))
}

// ArchitectureGTE applies the GTE predicate on the "architecture" field.
func ArchitectureGTE(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldArchitecture, v))
}

// ArchitectureLT applies the LT predicate on the "architecture" field.
func ArchitectureLT(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldArchitecture, v))
}

// ArchitectureLTE applies the LTE predicate on the "architecture" field.
func ArchitectureLTE(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldArchitecture, v))
}

// ArchitectureContains applies the Contains predicate on the "architecture" field.
func ArchitectureContains(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldContains(FieldArchitecture, v))
}

// ArchitectureHasPrefix applies the HasPrefix predicate on the "architecture" field.
func ArchitectureHasPrefix(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldHasPrefix(FieldArchitecture, v))
}

// ArchitectureHasSuffix applies the HasSuffix predicate on the "architecture" field.
func ArchitectureHasSuffix(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldHasSuffix(FieldArchitecture, v))
}

// ArchitectureEqualFold applies the EqualFold predicate on the "architecture" field.
func ArchitectureEqualFold(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEqualFold(FieldArchitecture, v))
}

// ArchitectureContainsFold applies the ContainsFold predicate on the "architecture" field.
func ArchitectureContainsFold(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldContainsFold(FieldArchitecture, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldHasSuffix(FieldModel, v))
}

// ModelIsNil applies the IsNil predicate on the "model" field.
func ModelIsNil() predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIsNull(FieldModel))
}

// ModelNotNil applies the NotNil predicate on the "model" field.
func ModelNotNil() predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotNull(FieldModel))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldContainsFold(FieldModel, v))
}

// BoardNameEQ applies the EQ predicate on the "board_name" field.
func BoardNameEQ(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldBoardName, v))
}

// BoardNameNEQ applies the NEQ predicate on the "board_name" field.
func BoardNameNEQ(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldBoardName, v))
}

// BoardNameIn applies the In predicate on the "board_name" field.
func BoardNameIn(vs ...string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldBoardName, vs...))
}

// BoardNameNotIn applies the NotIn predicate on the "board_name" field.
func BoardNameNotIn(vs ...string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldBoardName, vs...))
}

// BoardNameGT applies the GT predicate on the "board_name" field.
func BoardNameGT(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldBoardName, v))
}

// BoardNameGTE applies the GTE predicate on the "board_name" field.
func BoardNameGTE(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldBoardName, v))
}

// BoardNameLT applies the LT predicate on the "board_name" field.
func BoardNameLT(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldBoardName, v))
}

// BoardNameLTE applies the LTE predicate on the "board_name" field.
func BoardNameLTE(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldBoardName, v))
}

// BoardNameContains applies the Contains predicate on the "board_name" field.
func BoardNameContains(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldContains(FieldBoardName, v))
}

// BoardNameHasPrefix applies the HasPrefix predicate on the "board_name" field.
func BoardNameHasPrefix(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldHasPrefix(FieldBoardName, v))
}

// BoardNameHasSuffix applies the HasSuffix predicate on the "board_name" field.
func BoardNameHasSuffix(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldHasSuffix(FieldBoardName, v))
}

// BoardNameIsNil applies the IsNil predicate on the "board_name" field.
func BoardNameIsNil() predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIsNull(FieldBoardName))
}

// BoardNameNotNil applies the NotNil predicate on the "board_name" field.
func BoardNameNotNil() predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotNull(FieldBoardName))
}

// BoardNameEqualFold applies the EqualFold predicate on the "board_name" field.
func BoardNameEqualFold(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEqualFold(FieldBoardName, v))
}

// BoardNameContainsFold applies the ContainsFold predicate on the "board_name" field.
func BoardNameContainsFold(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldContainsFold(FieldBoardName, v))
}

// TotalMemoryEQ applies the EQ predicate on the "total_memory" field.
func TotalMemoryEQ(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldTotalMemory, v))
}

// TotalMemoryNEQ applies the NEQ predicate on the "total_memory" field.
func TotalMemoryNEQ(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldTotalMemory, v))
}

// TotalMemoryIn applies the In predicate on the "total_memory" field.
func TotalMemoryIn(vs ...int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldTotalMemory, vs...))
}

// TotalMemoryNotIn applies the NotIn predicate on the "total_memory" field.
func TotalMemoryNotIn(vs ...int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldTotalMemory, vs...))
}

// TotalMemoryGT applies the GT predicate on the "total_memory" field.
func TotalMemoryGT(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldTotalMemory, v))
}

// TotalMemoryGTE applies the GTE predicate on the "total_memory" field.
func TotalMemoryGTE(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldTotalMemory, v))
}

// TotalMemoryLT applies the LT predicate on the "total_memory" field.
func TotalMemoryLT(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldTotalMemory, v))
}

// TotalMemoryLTE applies the LTE predicate on the "total_memory" field.
func TotalMemoryLTE(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldTotalMemory, v))
}

// AvailableStorageEQ applies the EQ predicate on the "available_storage" field.
func AvailableStorageEQ(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldAvailableStorage, v))
}

// AvailableStorageNEQ applies the NEQ predicate on the "available_storage" field.
func AvailableStorageNEQ(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldAvailableStorage, v))
}

// AvailableStorageIn applies the In predicate on the "available_storage" field.
func AvailableStorageIn(vs ...int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldAvailableStorage, vs...))
}

// AvailableStorageNotIn applies the NotIn predicate on the "available_storage" field.
func AvailableStorageNotIn(vs ...int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldAvailableStorage, vs...))
}

// AvailableStorageGT applies the GT predicate on the "available_storage" field.
func AvailableStorageGT(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldAvailableStorage, v))
}

// AvailableStorageGTE applies the GTE predicate on the "available_storage" field.
func AvailableStorageGTE(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldAvailableStorage, v))
}

// AvailableStorageLT applies the LT predicate on the "available_storage" field.
func AvailableStorageLT(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldAvailableStorage, v))
}

// AvailableStorageLTE applies the LTE predicate on the "available_storage" field.
func AvailableStorageLTE(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldAvailableStorage, v))
}

// CPUCountEQ applies the EQ predicate on the "cpu_count" field.
func CPUCountEQ(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldCPUCount, v))
}

// CPUCountNEQ applies the NEQ predicate on the "cpu_count" field.
func CPUCountNEQ(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldCPUCount, v))
}

// CPUCountIn applies the In predicate on the "cpu_count" field.
func CPUCountIn(vs ...int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldCPUCount, vs...))
}

// CPUCountNotIn applies the NotIn predicate on the "cpu_count" field.
func CPUCountNotIn(vs ...int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldCPUCount, vs...))
}

// CPUCountGT applies the GT predicate on the "cpu_count" field.
func CPUCountGT(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldCPUCount, v))
}

// CPUCountGTE applies the GTE predicate on the "cpu_count" field.
func CPUCountGTE(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldCPUCount, v))
}

// CPUCountLT applies the LT predicate on the "cpu_count" field.
func CPUCountLT(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldCPUCount, v))
}

// CPUCountLTE applies the LTE predicate on the "cpu_count" field.
func CPUCountLTE(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldCPUCount, v))
}

// HasWirelessChipEQ applies the EQ predicate on the "has_wireless_chip" field.
func HasWirelessChipEQ(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldHasWirelessChip, v))
}

// HasWirelessChipNEQ applies the NEQ predicate on the "has_wireless_chip" field.
func HasWirelessChipNEQ(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldHasWirelessChip, v))
}

// HasLteModuleEQ applies the EQ predicate on the "has_lte_module" field.
func HasLteModuleEQ(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldHasLteModule, v))
}

// HasLteModuleNEQ applies the NEQ predicate on the "has_lte_module" field.
func HasLteModuleNEQ(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldHasLteModule, v))
}

// VersionRawEQ applies the EQ predicate on the "version_raw" field.
func VersionRawEQ(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldVersionRaw, v))
}

// VersionRawNEQ applies the NEQ predicate on the "version_raw" field.
func VersionRawNEQ(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldVersionRaw, v))
}

// VersionRawIn applies the In predicate on the "version_raw" field.
func VersionRawIn(vs ...string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldVersionRaw, vs...))
}

// VersionRawNotIn applies the NotIn predicate on the "version_raw" field.
func VersionRawNotIn(vs ...string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldVersionRaw, vs...))
}

// VersionRawGT applies the GT predicate on the "version_raw" field.
func VersionRawGT(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldVersionRaw, v))
}

// VersionRawGTE applies the GTE predicate on the "version_raw" field.
func VersionRawGTE(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldVersionRaw, v))
}

// VersionRawLT applies the LT predicate on the "version_raw" field.
func VersionRawLT(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldVersionRaw, v))
}

// VersionRawLTE applies the LTE predicate on the "version_raw" field.
func VersionRawLTE(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldVersionRaw, v))
}

// VersionRawContains applies the Contains predicate on the "version_raw" field.
func VersionRawContains(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldContains(FieldVersionRaw, v))
}

// VersionRawHasPrefix applies the HasPrefix predicate on the "version_raw" field.
func VersionRawHasPrefix(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldHasPrefix(FieldVersionRaw, v))
}

// VersionRawHasSuffix applies the HasSuffix predicate on the "version_raw" field.
func VersionRawHasSuffix(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldHasSuffix(FieldVersionRaw, v))
}

// VersionRawEqualFold applies the EqualFold predicate on the "version_raw" field.
func VersionRawEqualFold(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEqualFold(FieldVersionRaw, v))
}

// VersionRawContainsFold applies the ContainsFold predicate on the "version_raw" field.
func VersionRawContainsFold(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldContainsFold(FieldVersionRaw, v))
}

// VersionMajorEQ applies the EQ predicate on the "version_major" field.
func VersionMajorEQ(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldVersionMajor, v))
}

// VersionMajorNEQ applies the NEQ predicate on the "version_major" field.
func VersionMajorNEQ(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldVersionMajor, v))
}

// VersionMajorIn applies the In predicate on the "version_major" field.
func VersionMajorIn(vs ...int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldVersionMajor, vs...))
}

// VersionMajorNotIn applies the NotIn predicate on the "version_major" field.
func VersionMajorNotIn(vs ...int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldVersionMajor, vs...))
}

// VersionMajorGT applies the GT predicate on the "version_major" field.
func VersionMajorGT(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldVersionMajor, v))
}

// VersionMajorGTE applies the GTE predicate on the "version_major" field.
func VersionMajorGTE(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldVersionMajor, v))
}

// VersionMajorLT applies the LT predicate on the "version_major" field.
func VersionMajorLT(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldVersionMajor, v))
}

// VersionMajorLTE applies the LTE predicate on the "version_major" field.
func VersionMajorLTE(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldVersionMajor, v))
}

// VersionMinorEQ applies the EQ predicate on the "version_minor" field.
func VersionMinorEQ(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldVersionMinor, v))
}

// VersionMinorNEQ applies the NEQ predicate on the "version_minor" field.
func VersionMinorNEQ(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldVersionMinor, v))
}

// VersionMinorIn applies the In predicate on the "version_minor" field.
func VersionMinorIn(vs ...int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldVersionMinor, vs...))
}

// VersionMinorNotIn applies the NotIn predicate on the "version_minor" field.
func VersionMinorNotIn(vs ...int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldVersionMinor, vs...))
}

// VersionMinorGT applies the GT predicate on the "version_minor" field.
func VersionMinorGT(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldVersionMinor, v))
}

// VersionMinorGTE applies the GTE predicate on the "version_minor" field.
func VersionMinorGTE(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldVersionMinor, v))
}

// VersionMinorLT applies the LT predicate on the "version_minor" field.
func VersionMinorLT(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldVersionMinor, v))
}

// VersionMinorLTE applies the LTE predicate on the "version_minor" field.
func VersionMinorLTE(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldVersionMinor, v))
}

// VersionPatchEQ applies the EQ predicate on the "version_patch" field.
func VersionPatchEQ(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldVersionPatch, v))
}

// VersionPatchNEQ applies the NEQ predicate on the "version_patch" field.
func VersionPatchNEQ(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldVersionPatch, v))
}

// VersionPatchIn applies the In predicate on the "version_patch" field.
func VersionPatchIn(vs ...int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldVersionPatch, vs...))
}

// VersionPatchNotIn applies the NotIn predicate on the "version_patch" field.
func VersionPatchNotIn(vs ...int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldVersionPatch, vs...))
}

// VersionPatchGT applies the GT predicate on the "version_patch" field.
func VersionPatchGT(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldVersionPatch, v))
}

// VersionPatchGTE applies the GTE predicate on the "version_patch" field.
func VersionPatchGTE(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldVersionPatch, v))
}

// VersionPatchLT applies the LT predicate on the "version_patch" field.
func VersionPatchLT(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldVersionPatch, v))
}

// VersionPatchLTE applies the LTE predicate on the "version_patch" field.
func VersionPatchLTE(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldVersionPatch, v))
}

// LicenseLevelEQ applies the EQ predicate on the "license_level" field.
func LicenseLevelEQ(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldLicenseLevel, v))
}

// LicenseLevelNEQ applies the NEQ predicate on the "license_level" field.
func LicenseLevelNEQ(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldLicenseLevel, v))
}

// LicenseLevelIn applies the In predicate on the "license_level" field.
func LicenseLevelIn(vs ...int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldLicenseLevel, vs...))
}

// LicenseLevelNotIn applies the NotIn predicate on the "license_level" field.
func LicenseLevelNotIn(vs ...int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldLicenseLevel, vs...))
}

// LicenseLevelGT applies the GT predicate on the "license_level" field.
func LicenseLevelGT(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldLicenseLevel, v))
}

// LicenseLevelGTE applies the GTE predicate on the "license_level" field.
func LicenseLevelGTE(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldLicenseLevel, v))
}

// LicenseLevelLT applies the LT predicate on the "license_level" field.
func LicenseLevelLT(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldLicenseLevel, v))
}

// LicenseLevelLTE applies the LTE predicate on the "license_level" field.
func LicenseLevelLTE(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldLicenseLevel, v))
}

// UpdateChannelEQ applies the EQ predicate on the "update_channel" field.
func UpdateChannelEQ(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldUpdateChannel, v))
}

// UpdateChannelNEQ applies the NEQ predicate on the "update_channel" field.
func UpdateChannelNEQ(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldUpdateChannel, v))
}

// UpdateChannelIn applies the In predicate on the "update_channel" field.
func UpdateChannelIn(vs ...string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldUpdateChannel, vs...))
}

// UpdateChannelNotIn applies the NotIn predicate on the "update_channel" field.
func UpdateChannelNotIn(vs ...string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldUpdateChannel, vs...))
}

// UpdateChannelGT applies the GT predicate on the "update_channel" field.
func UpdateChannelGT(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldUpdateChannel, v))
}

// UpdateChannelGTE applies the GTE predicate on the "update_channel" field.
func UpdateChannelGTE(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldUpdateChannel, v))
}

// UpdateChannelLT applies the LT predicate on the "update_channel" field.
func UpdateChannelLT(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldUpdateChannel, v))
}

// UpdateChannelLTE applies the LTE predicate on the "update_channel" field.
func UpdateChannelLTE(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldUpdateChannel, v))
}

// UpdateChannelContains applies the Contains predicate on the "update_channel" field.
func UpdateChannelContains(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldContains(FieldUpdateChannel, v))
}

// UpdateChannelHasPrefix applies the HasPrefix predicate on the "update_channel" field.
func UpdateChannelHasPrefix(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldHasPrefix(FieldUpdateChannel, v))
}

// UpdateChannelHasSuffix applies the HasSuffix predicate on the "update_channel" field.
func UpdateChannelHasSuffix(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldHasSuffix(FieldUpdateChannel, v))
}

// UpdateChannelIsNil applies the IsNil predicate on the "update_channel" field.
func UpdateChannelIsNil() predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIsNull(FieldUpdateChannel))
}

// UpdateChannelNotNil applies the NotNil predicate on the "update_channel" field.
func UpdateChannelNotNil() predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotNull(FieldUpdateChannel))
}

// UpdateChannelEqualFold applies the EqualFold predicate on the "update_channel" field.
func UpdateChannelEqualFold(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEqualFold(FieldUpdateChannel, v))
}

// UpdateChannelContainsFold applies the ContainsFold predicate on the "update_channel" field.
func UpdateChannelContainsFold(v string) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldContainsFold(FieldUpdateChannel, v))
}

// ContainerPackageInstalledEQ applies the EQ predicate on the "container_package_installed" field.
func ContainerPackageInstalledEQ(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldContainerPackageInstalled, v))
}

// ContainerPackageInstalledNEQ applies the NEQ predicate on the "container_package_installed" field.
func ContainerPackageInstalledNEQ(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldContainerPackageInstalled, v))
}

// ContainerEnabledEQ applies the EQ predicate on the "container_enabled" field.
func ContainerEnabledEQ(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldContainerEnabled, v))
}

// ContainerEnabledNEQ applies the NEQ predicate on the "container_enabled" field.
func ContainerEnabledNEQ(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldContainerEnabled, v))
}

// ContainerRegistryConfiguredEQ applies the EQ predicate on the "container_registry_configured" field.
func ContainerRegistryConfiguredEQ(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldContainerRegistryConfigured, v))
}

// ContainerRegistryConfiguredNEQ applies the NEQ predicate on the "container_registry_configured" field.
func ContainerRegistryConfiguredNEQ(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldContainerRegistryConfigured, v))
}

// ContainerStorageAvailableEQ applies the EQ predicate on the "container_storage_available" field.
func ContainerStorageAvailableEQ(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldContainerStorageAvailable, v))
}

// ContainerStorageAvailableNEQ applies the NEQ predicate on the "container_storage_available" field.
func ContainerStorageAvailableNEQ(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldContainerStorageAvailable, v))
}

// ContainerStorageAvailableIn applies the In predicate on the "container_storage_available" field.
func ContainerStorageAvailableIn(vs ...int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldContainerStorageAvailable, vs...))
}

// ContainerStorageAvailableNotIn applies the NotIn predicate on the "container_storage_available" field.
func ContainerStorageAvailableNotIn(vs ...int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldContainerStorageAvailable, vs...))
}

// ContainerStorageAvailableGT applies the GT predicate on the "container_storage_available" field.
func ContainerStorageAvailableGT(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldContainerStorageAvailable, v))
}

// ContainerStorageAvailableGTE applies the GTE predicate on the "container_storage_available" field.
func ContainerStorageAvailableGTE(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldContainerStorageAvailable, v))
}

// ContainerStorageAvailableLT applies the LT predicate on the "container_storage_available" field.
func ContainerStorageAvailableLT(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldContainerStorageAvailable, v))
}

// ContainerStorageAvailableLTE applies the LTE predicate on the "container_storage_available" field.
func ContainerStorageAvailableLTE(v int64) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldContainerStorageAvailable, v))
}

// SupportsNetworkNamespaceEQ applies the EQ predicate on the "supports_network_namespace" field.
func SupportsNetworkNamespaceEQ(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldSupportsNetworkNamespace, v))
}

// SupportsNetworkNamespaceNEQ applies the NEQ predicate on the "supports_network_namespace" field.
func SupportsNetworkNamespaceNEQ(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldSupportsNetworkNamespace, v))
}

// MaxContainersEQ applies the EQ predicate on the "max_containers" field.
func MaxContainersEQ(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldMaxContainers, v))
}

// MaxContainersNEQ applies the NEQ predicate on the "max_containers" field.
func MaxContainersNEQ(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldMaxContainers, v))
}

// MaxContainersIn applies the In predicate on the "max_containers" field.
func MaxContainersIn(vs ...int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldMaxContainers, vs...))
}

// MaxContainersNotIn applies the NotIn predicate on the "max_containers" field.
func MaxContainersNotIn(vs ...int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldMaxContainers, vs...))
}

// MaxContainersGT applies the GT predicate on the "max_containers" field.
func MaxContainersGT(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldMaxContainers, v))
}

// MaxContainersGTE applies the GTE predicate on the "max_containers" field.
func MaxContainersGTE(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldMaxContainers, v))
}

// MaxContainersLT applies the LT predicate on the "max_containers" field.
func MaxContainersLT(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldMaxContainers, v))
}

// MaxContainersLTE applies the LTE predicate on the "max_containers" field.
func MaxContainersLTE(v int) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldMaxContainers, v))
}

// DetectedAtEQ applies the EQ predicate on the "detected_at" field.
func DetectedAtEQ(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldDetectedAt, v))
}

// DetectedAtNEQ applies the NEQ predicate on the "detected_at" field.
func DetectedAtNEQ(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldDetectedAt, v))
}

// DetectedAtIn applies the In predicate on the "detected_at" field.
func DetectedAtIn(vs ...time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldDetectedAt, vs...))
}

// DetectedAtNotIn applies the NotIn predicate on the "detected_at" field.
func DetectedAtNotIn(vs ...time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldDetectedAt, vs...))
}

// DetectedAtGT applies the GT predicate on the "detected_at" field.
func DetectedAtGT(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldDetectedAt, v))
}

// DetectedAtGTE applies the GTE predicate on the "detected_at" field.
func DetectedAtGTE(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldDetectedAt, v))
}

// DetectedAtLT applies the LT predicate on the "detected_at" field.
func DetectedAtLT(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldDetectedAt, v))
}

// DetectedAtLTE applies the LTE predicate on the "detected_at" field.
func DetectedAtLTE(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldDetectedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldExpiresAt, v))
}

// IsRefreshingEQ applies the EQ predicate on the "is_refreshing" field.
func IsRefreshingEQ(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldIsRefreshing, v))
}

// IsRefreshingNEQ applies the NEQ predicate on the "is_refreshing" field.
func IsRefreshingNEQ(v bool) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldIsRefreshing, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RouterCapability {
	return predicate.RouterCapability(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RouterCapability) predicate.RouterCapability {
	return predicate.RouterCapability(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RouterCapability) predicate.RouterCapability {
	return predicate.RouterCapability(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RouterCapability) predicate.RouterCapability {
	return predicate.RouterCapability(sql.NotPredicates(p))
}
